### ISSUE TITLE
Gutenberg: Block Availability task list

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack#10198]
Individual development tasks from pafL3P-1X-p2
Related discussion: p1HpG7-5JG-p2

## Tasks
1. [x] Do not register blocks when Jetpack is not connected (#10195)
2. [ ] Expose data about which blocks should be available based on modules (#10327, https://github.com/Automattic/wp-calypso/pull/27875)
3. [ ] Read and respect exposed block activation data
4. [x] Consider Jetpack development mode

## Punted
- Expose module API so blocks can query and update modules
- Expose module data to blocks so they can behave accordingly.
  - Overridden deactivated modules are never registered.
  - When a block that depends on a module is inserted, it activates the corresponding module in the background.

~~@Automattic/luna~~ @Automattic/poseidon

**Comment by tyxla** [comment]
Added a "Consider Jetpack development mode" item, as suggested by @jeherve in p1HpG7-5EW-p2  #comment-27930

**Comment by aldavigdis** [comment]
For reference, I just referred this ticket at https://github.com/Automattic/jetpack/issues/8764.

Just talked to @roccotripaldi and asked him for a sister global of the "available blocks" array for determining the WordPress.com or Jetpack plan in use, so we can facilitate the VideoPress block as well as other work.

**Comment by sirreal** [comment]
@roccotripaldi or @aldavigdis I think this is settled, shall we close?

**Comment by roccotripaldi** [comment]
Yes, let's close it!
I'm tracking additional tasks on p1HpG7-5Nf-p2 for now, and i'll create additional Git issues as needed.
