### ISSUE TITLE
Gutenberg: add blocks to Jetpack

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10326]
Using this issue as a list of the things that should be addressed for the release of the first Gutenberg blocks in Jetpack. It is not a complete list, but aims to list the things that are higher on the priority list right now.

For more details, view Gutenberg project board for Jetpack:
https://github.com/orgs/Automattic/projects/53

### Infrastructure

- [x] Block Availability task list #10198
- [x] Enqueue blocks' scripts and styles conditionally #10325 (fix part 1 #10328, part 2 #10405)
- [x] Handle i18n: blocks need to be translateable https://github.com/Automattic/wp-calypso/issues/27814
- [x] Add Jetpack branding to blocks https://github.com/Automattic/wp-calypso/pull/27878, https://github.com/Automattic/wp-calypso/issues/27773 and #9584

### Blocks

Here is a list of the blocks in progress:

- [x] Contact form: #10537 / https://github.com/Automattic/wp-calypso/pull/27996
- [x] Tiled Galleries #10145 / https://github.com/Automattic/wp-calypso/pull/27458 
- [x] Markdown https://github.com/Automattic/wp-calypso/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3AJetpack+label%3A%22%5BGoal%5D+Gutenberg%22+markdown+is%3Aopen
- [x] Map #10319 / https://github.com/Automattic/wp-calypso/pull/28498
- [x] Related Posts #10132
- [x] Publicize #9039
- [ ] VideoPress #8764
- [x] Simple Payments #10402 / https://github.com/Automattic/wp-calypso/pull/28169 
- [x] VR https://github.com/Automattic/wp-calypso/pull/27873

### Bugs with existing features

Here is a list of the current bugs with existing Jetpack features:

- [x] General: when Jetpack is active, part of the contextual toolbar is missing from Text block #10549
- [x] After the Deadline: request is made to AtD when module is deactivated #10548
- [x] Carousel: does not work with Gallery block. #10246
- [x] Photon: ensure compatibility with Block editor #10580
- [ ] After the Deadline not triggered in Gutenberg editor. #9128 
- [x] VR Shortcode: issues with latest version of Gutenberg. #9935 
- [x] Simple Payments: shortcode in Gutenberg fails PayPal script #10481
- [ ] Gist: all gist embeds broken. #10161
- [ ] Instagram: all Instagram embeds broken. #9331

**Comment by jeherve** [comment]
Closing as we've now added most of the blocks on this list, and have stopped using this issue as a master list of all blocks to come.
