### ISSUE TITLE
Theme Tools / Infinite Scroll: add support for Twenty Nineteen

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10335]
Twenty Nineteen is expected to ship with WordPress 5.0 in November. It is currently being developed here:
https://github.com/WordPress/twentynineteen

In the past, and with previous default themes, we've added a number of compatibility files and functions to make sure new WordPress site owners had the best experience they could get when using the default theme and Jetpack. In practice, it meant adding the following:

- [x] Add Infinite Scroll support and tweak CSS to make sure the IS buttons look good.
- [x] Add support for Responsive Videos.
- [x] Alter Gallery widget default width.
- [x] Style widgets and shortcodes to match the style of the theme.
- [x] Cookie widget text smaller than the rest of the theme's elements #10513
- [x] Authors / RSS Widget: improve layout #10522
- [x] Related Posts / Twenty Nineteen: layout issues #10585
- [ ] Shortcodes: Remove margins #10485

There are also things we haven't done for previous default themes, but may want to do for this one:

- [ ] Add Social Menu Support
- [x] Add Content Options support

See how it was done for Twenty Sixteen for example: #2970

**Comment by davidakennedy** [comment]
Hey @jeherve, thanks for creating this. @allancole will be working on it as part of his work on Twenty Nineteen.

One question I have is around the "Alter Gallery widget default width." Why would that be necessary? Have we needed to do that before?

**Comment by jeherve** [comment]
This is probably something that we could drop for this theme; it is less important now. 

As a bit of background, Jetpack used to have its own Gallery widget, and that widget had a default width setting that could be overwritten via a filter to match the exact width of your sidebar. Here is how it looked for Twenty Sixteen for example:
https://github.com/Automattic/jetpack/blob/55c1837cc77318540c2dd28734617f422159c91e/modules/theme-tools/compat/twentysixteen.php#L37-L43

WordPress Core then introduced its own Gallery widget in WP 4.9, and we worked to migrate all old Jetpack Gallery widgets to the new Core Gallery widget (related PR: #8062). Only folks running WP 4.8 or forcing the old Jetpack widget on via [this filter](https://developer.jetpack.com/hooks/jetpack_force_enable_gallery_widget/) now use the old Jetpack Gallery Widget. It consequently may not be worth adding compatibility to that old widget in the new default theme. It's only a few lines where you define the max width of your sidebar though, but we may not need that at all. I'll let you make that call. 👍

**Comment by jeherve** [comment]
Here is a related issue: #10513

**Comment by crunnells** [comment]
@jeherve Both of those issues (#10513 and #10522) should be resolved now

**Comment by jeherve** [comment]
One item remains on that list, but we can tackle it later on:
https://github.com/Automattic/jetpack/issues/10485
