### ISSUE TITLE
PHP 7.3 Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#10729]
PHP 7.3 is coming soon, let's make sure we are fully compatible:
https://wiki.php.net/todo/php73

Related: #6106, #8156

*If you want to help with a PR, please edit this description and add the PR number between parens at the end of the line*

**Warnings** 

- [x] - Warning: "continue" targeting switch is equivalent to "break". #10730

**Unit Tests**

- [x] - Adding PHP 7.3 testing with Travis #10723

**Other**

- [x] - Update phpcompatibility to test for 7.3 #10234
