### ISSUE TITLE
Publicize / Sharing: remove Google Plus. Google Plus is being shut down in early March.

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#10950]
Google is [discontinuing the Google Plus service](https://www.blog.google/technology/safety-security/expediting-changes-google-plus/) in early March.

Internal reference: p58i-7iC-p2

We should remove the ability to create new Google Plus connections, and then remove the ability to use those connections, and finally remove all the tokens and configuration information.

- [x] #10951 Show deprecation notice on Google+ Publicize screen
- [x] #11184 Comments: remove Google+ data from the Comment module.
- [x] #11200 Sharing: Deprecate Google+ Sharing Button
- [x] #11202 WIP: Widgets: Remove Google+ Badge

**Comment by jeherve** [comment]
Edited to clarify: we'll need to make changes to Publicize, as started in #10951, but we'll also need to remove the Google+ sharing button.

**Comment by jeherve** [comment]
Noting that we will also need to remove a few other things:
- The Google+ option in the comment form.
- The Google+ embed https://github.com/Automattic/jetpack/blob/branch-6.9/modules/shortcodes/googleplus.php
- The Google+ badge https://github.com/Automattic/jetpack/blob/branch-6.9/modules/widgets/googleplus-badge.php

**Comment by niallkennedy** [comment]
for completeness, you might also be interested in:

- google-plus-1 Sharedaddy service
- google_plus social links theme tool
- Google+ genericon
- Google+ social logo

Intermittent failures begin as soon as January 28 https://developers.google.com/+/integrations-shutdown

**Comment by jeherve** [comment]
Closing as it's all been addressed now.
