### ISSUE TITLE
[Shortcopy] - 7.2 Connection banner / page improvements [master issue] 

### ISSUE THREAD

**Issue by jeffgolenski** [Automattic/jetpack#11614]
@eliorivero Your initial take in the [updated connection banner](https://github.com/Automattic/jetpack/pull/11573) is fantastic. I just missed a few details that we should improve before the launch.

1 Connection banner content improvements
======

**Headline** 

<img width="1491" alt="Screen Shot 2019-03-19 at 1 23 57 PM" src="https://user-images.githubusercontent.com/214813/54627698-53793b00-4a4a-11e9-9661-87ea6391cf2c.png">

Currently the headline is lacking the security and performance focus

> You’re almost done. Set up Jetpack to boost your site performance and unlock powerful customization, marketing, and security tools.

_should be..._

> You’re almost done. Set up Jetpack to enable powerful security and performance tools for WordPress.

**Content**

Per @michelleweber's [editorial review here](https://github.com/Automattic/jetpack/issues/11537#issuecomment-473097680)

> Jetpack protects you against brute force attacks and unauthorized logins. Basic protection is always free, while premium plans add unlimited backups of your whole site, spam protection, malware scanning, and automated fixes.

> Activate site accelerator tools and watch your page load times and hosting costs drop -- we'll optimize your images and serve them from our own powerful global network of servers, and speed up your mobile site to reduce bandwidth usage.

**Content checklist:**
- [x] Headline adjustments
- [x] Content adjustments

2 Connection banner content padding & style adjustments
======

<img width="1506" alt="Screen Shot 2019-03-19 at 1 38 54 PM" src="https://user-images.githubusercontent.com/214813/54628694-73116300-4a4c-11e9-9d01-4d6fd636e0c9.png">

<img width="1501" alt="Screen Shot 2019-03-19 at 1 40 11 PM" src="https://user-images.githubusercontent.com/214813/54628801-a227d480-4a4c-11e9-9d5e-38893bb5b82a.png">

- [x] content area ( `jp-wpcom-connect__slide-text`) left padding of `rem( 45px )` to give some breathing room between the content and illo. large screen only.
- [x] A little more breathing room between last content paragraph and "Set up button" I think 2rem is nice. 

3 Jetpack dashboard: pre-connection screen
======

<img width="1667" alt="Screen Shot 2019-03-19 at 2 02 03 PM" src="https://user-images.githubusercontent.com/214813/54630196-a7d2e980-4a4f-11e9-9142-f6eaab4de413.png">

- [x] hide Apps block from displaying on pre-connection screen. We want them to do one thing and one thing only here, connect jetpack. 

4 Plugins: Full screen connection
======

![Screen Shot 2019-03-19 at 2 57 34 PM](https://user-images.githubusercontent.com/214813/54634017-b1604f80-4a57-11e9-9ea6-a71a7486c225.png)

- [x] Give `jp-connect-full__row` some limitation. `max-width: 100px; margin: 0 auto;` to avoid illos and text getting too large. [Solution preview](https://cloudup.com/cnHJ0_pbsQK)
