### ISSUE TITLE
WordPress 5.3 Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#13597]
WordPress 5.3 is currently scheduled to ship November 12 2019, and will include changes that we should aim to support in Jetpack.

I am creating this Master Issue to help me keep track of all those changes:

- [x] Date/Time functionality changes #13513
- [x] Block Editor: support block previews #13510 
- [x] Themes: full compatibility with Twenty Twenty #13511 
- [x] Carousel: support Gallery block markup changes #13582
- [x] SSO: Login form changes #13551 
- [x] Visual regressions in blocks #13618 
- [x] API: ensure compatibility with spread operator changes in WP 5.3 #13694
- [x] Photon: Ensure compat and optimizations with 5.3 #13701
- [x] Calypsoify: update to be compatible with WordPress 5.3 admin CSS changes #13704 
- [x] Dashboard: update Jetpack button and card styles to match WordPress 5.3 #13729
- [x] Widgets: add aria-current attribute to links when on same page #13831

**Comment by simison** [comment]
Might need reviewing: https://make.wordpress.org/core/2019/10/09/wp-5-3-introducing-the-spread-operator/

**Comment by jeherve** [comment]
@simison Good Call. Noted in #13694

**Comment by kraftbj** [comment]
Only slightly related but we can get a tiny performance boost by using the spread operator ourselves: https://github.com/Automattic/jetpack/pull/13699

The most gain would be to XML-RPC but we can't optimize that until Core does since we extend their IXR classes.

**Comment by simison** [comment]
Is [this `listenTo`](https://github.com/Automattic/jetpack/blob/58638f46094b36f5df9cbc4570006544f0ad300c/_inc/jetpack-modules.views.js#L57) affected by https://make.wordpress.org/core/2019/10/10/wordpress-5-3-backbone-upgrade-guide/?

**Comment by jeherve** [comment]
@simison No, it seems okay in my tests. 👍

**Comment by jeherve** [comment]
https://make.wordpress.org/core/2019/10/15/changes-to-wp_die-html-output-in-wordpress-5-3/
> With WordPress 5.3, error messages are wrapped in a `<div>` rather than a `<p>`

This doesn't seem to impact us. 👍
