### ISSUE TITLE
Gutenberg extensions: visual regressions in Gutenberg 6.5 (=WP 5.3)   

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#13618]
I'm using Gutenberg 6.5 plugin on WP 5.2 to test, which should be pretty close to WP 5.3 block editor.

Using TwentyNineteen theme and Chrome browser to test. [Back to the theme](https://wordpress.org/plugins/back-to-the-theme/) might be a handy tool if you need to test several default themes.

I didn't test WordAds, VideoPress, Publicize, Likes&Sharing, short url.

- [x] Jetpack GIF block - fix alignment of search field and search button #13646
- [x] Jetpack Map block - fix close icon alignment #13647
- [x] Jetpack Contact Form block - fix gap between field name and required text #13648
- [x] Jetpack Map block - fix tiny Mapbox location marker popover close icon #13650
- [x] Jetpack Repeat Visitor block - increase notice text size #13645 

### Gif
<img width="751" alt="Screenshot 2019-10-02 at 09 11 12" src="https://user-images.githubusercontent.com/87168/66021922-f1b78480-e4f4-11e9-80eb-b73b31239f01.png">
<img width="751" alt="Screenshot 2019-10-02 at 09 10 55" src="https://user-images.githubusercontent.com/87168/66021923-f1b78480-e4f4-11e9-89c5-b0f69bed5224.png">

### Form
**Before**
<img width="773" alt="Screenshot 2019-10-02 at 09 27 38" src="https://user-images.githubusercontent.com/87168/66022631-39d7a680-e4f7-11e9-9696-e54526b3dcfc.png">

**After**
<img width="787" alt="Screenshot 2019-10-02 at 09 23 14" src="https://user-images.githubusercontent.com/87168/66022637-40feb480-e4f7-11e9-87d5-33758f1a01ce.png">

### All blocks

Support reference links are now out of place in block previews:

<img width="714" alt="Screenshot 2019-10-02 at 09 15 30" src="https://user-images.githubusercontent.com/87168/66022054-625ea100-e4f5-11e9-94e5-06fc1de2b724.png">

The description field should really be just text and the support link should be in its own panel. I had a proposal to standardize it but never found time to finish it: https://github.com/WordPress/gutenberg/pull/11330. See also https://github.com/Automattic/wp-calypso/pull/28416

## Regressions unrelated to Gutenberg v6.5/WP 5.3 but I'll list here anyway
Might be related to previous updates or updates in themes also theme updates, didn't investigate:

### Map
<img width="365" alt="Screenshot 2019-10-02 at 09 10 24" src="https://user-images.githubusercontent.com/87168/66021929-f54b0b80-e4f4-11e9-9f98-eac33d0ba6e0.png">
<img width="389" alt="Screenshot 2019-10-02 at 09 25 18" src="https://user-images.githubusercontent.com/87168/66022650-4bb94980-e4f7-11e9-9870-a608c763da16.png">

### Tiled gallery
<img width="566" alt="Screenshot 2019-10-02 at 09 21 49" src="https://user-images.githubusercontent.com/87168/66022647-4825c280-e4f7-11e9-81f9-432a574477db.png">

### Business hour
Align issues:
<img width="797" alt="Screenshot 2019-10-02 at 09 20 58" src="https://user-images.githubusercontent.com/87168/66022681-612e7380-e4f7-11e9-8715-8bcf7d68b73b.png">

### Repeat visitor
Tiny text:

<img width="751" alt="Screenshot 2019-10-02 at 09 19 58" src="https://user-images.githubusercontent.com/87168/66022688-6c819f00-e4f7-11e9-8ee8-0a2d83970131.png">

cc @MichaelArestad @joanrho 
cc @kwight as these might be bugs also on wpcom.

**Comment by kwight** [comment]
@simison Yep, a quick sampling of a bunch of them show them to be issues on WP.com as well (generally, any issue for dotorg will an issue for us too, since we're just iframing the `wp-admin` view anyways). Thanks for the heads-up 👍

**Comment by kwight** [comment]
Added this to our backlog just for visibility.

**Comment by joanrho** [comment]
@simison This is really awesome and overlaps with several things we caught as well. Can I ask you to please separate each out as an issue so it's easier to address each one rather than grouping everything in one issue?

**Comment by simison** [comment]
@joanrho Yo! Thanks for splitting the issues! I'm just slow. :-)

**Comment by joanrho** [comment]
@simison No problem, just trying to help move things along. Hope you don't mind I also just edited your main post above to include #13645 (Increasing blue notice text size) as a checked off item that's been addressed (already merged).

**Comment by MichaelArestad** [comment]
Donezo

**Comment by simison** [comment]
Nicely done, @MichaelArestad @joanrho !
