### ISSUE TITLE
Ajax: Improve block search results

### ISSUE THREAD

**Issue by obenland** [Automattic/jetpack#14628]
As a writer, I'd like results of block searches to be more relevant to my queries, so blocks are easier for me to find.

#### Aceptence Criteria:
* Blocks in spreadsheet resource are updated with the noted search term(s).

#### How to Demo:
* Search for a representative list of blocks from the spreadsheet and show that they're now discoverable.

#### Tasks:
- [x]  Create spreadsheet with widgets & corresponding keywords. (@huguesvincent)
- [x] Explore design to take users out of the editor. (@davemart-in)
- [ ] Update Jetpack block search terms based on below resource.

#### Resources:
* [Spreadsheet with blocks and their new search terms](https://docs.google.com/spreadsheets/d/1yTGDMdz3CSF23A8ed37pNJhbzxb9NXAhNU4yA2wJpUk/edit#gid=1216493125).

More discussion: See Quick Wins in paYJgx-qn-p2
Discussion around contextually linking out from block search: paEFis-yy-p2

**Comment by simison** [comment]
A related issue in core: https://github.com/WordPress/gutenberg/issues/14868

**Comment by huguesvincent** [comment]
Added some search terms to be added [here](https://docs.google.com/spreadsheets/d/1yTGDMdz3CSF23A8ed37pNJhbzxb9NXAhNU4yA2wJpUk/edit#gid=1216493125) @obenland. This is really a non-issue so we can proceed asap on that bit. Thanks for your help on this!

**Comment by huguesvincent** [comment]
Hey @davemart-in  thanks for posting on Dotorg design about how to best point users to other sections. Using Tips feel like the right fit indeed. I was playing a bit with the idea and wanted to understand where the tip could actually pop up. This PR is also useful in that regard: 
https://github.com/WordPress/gutenberg/pull/17326

I am wondering if it has to be added as a tip on the right of the picker like on this example
![image](https://user-images.githubusercontent.com/10820560/74343480-6a83f280-4dab-11ea-83d8-bdc54eaf3d8c.png)

Or can the tip be directly within the block like suggested by @simison initially. I find the action to be more in-line and less confusing than a new section popping up. Something like this: 
![Picker tip](https://user-images.githubusercontent.com/10820560/74343565-8edfcf00-4dab-11ea-8535-954ceb88bfe9.jpg)

Also, can the Tip have hyperlink in them allowing users to be redirected from there?

**Comment by davemart-in** [comment]
> Explore design to take users out of the editor. (@davemart-in)

I created an issue here: https://github.com/WordPress/gutenberg/issues/20196
