### ISSUE TITLE
WordPress 5.4 Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#14653]
For reference, here is a list of the things we should work on to ensure full compatibility with the upcoming version of WordPress. 

Items checked are not impacting us, or already handled.

- [x] Deprecating `WP_Customize_New_Menu_Control`, `WP_Customize_New_Menu_Section`, and `wp.customize.Menus.NewMenuControl` ([reference](https://make.wordpress.org/core/2020/02/12/formal-deprecation-of-some-unused-customizer-classes-in-wordpress-5-4/)).
- [x] Enhancements to favicon handling ([reference](https://make.wordpress.org/core/2020/02/19/enhancements-to-favicon-handling-in-wordpress-5-4/)).
- [x] Better information about errors in `wp_login_failed` ([reference](https://make.wordpress.org/core/2020/02/26/miscellaneous-developer-focused-changes-in-wordpress-5-4/)) #14821 
- [x] Gutenberg -- legacy “editor-” classes ([reference](https://make.wordpress.org/core/2020/03/02/markup-and-style-related-changes/)) #14446 
- [x] Div with class edit-post-layout__content removed ([reference](https://make.wordpress.org/core/2020/03/02/markup-and-style-related-changes/))
- [x] Meta attribute sources deprecated ([reference](https://make.wordpress.org/core/2020/03/02/general-block-editor-api-updates/))
- [x] Deprecation of wordpress/nux ([reference](https://make.wordpress.org/core/2020/03/02/general-block-editor-api-updates/))
- [x] Blocks: Add support for Collections #14454 

Block Editor layout changes:

- [x] #14982
- [x] #14975 
- [x] #14976 
- [x] #14977 
- [x] #14978 (fix in #15315) 
- [x] #14979 

Noting that the scheduled release date is planned for 31 March 2020, before Jetpack 8.4 is supposed to go out. If blockers are announced in the next few weeks, we may need to organize a point release.

**Comment by simison** [comment]
Related https://github.com/Automattic/jetpack/issues/14668

**Comment by nielslange** [comment]
Related #14674
