### ISSUE TITLE
Search: Display matching post meta in the content field

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#14911]
Currently we display term matches from three sources: title, content, and comments.

<img width="708" alt="Screen Shot 2020-03-06 at 9 58 35 AM" src="https://user-images.githubusercontent.com/820871/76104761-29899300-5f91-11ea-907f-f57081851418.png">

However, we match against more than just those three fields. For various use cases we should also display matches against the post meta. A good example is when most of the post content is actually stored in post meta rather than in the post_content field of the DB. See https://github.com/Automattic/jetpack/issues/14741#issuecomment-595370384

I think this requires:
- [ ] add to the post meta spec a param that allows matching to be displayed for certain keys
- [ ] create a separate field that combines content and specific post meta (maybe we display other matches also?)
- [ ] switch over to this new field for doing the highlighting

**Comment by gibrown** [comment]
Match against post meta.

We match against more than just the three fields we currently show. For various use cases we should also display matches against the post meta. A good example is when most of the post content is actually stored in post meta rather than in the post_content field of the DB. See https://github.com/Automattic/jetpack/issues/14741#issuecomment-595370384

I think this requires:
- [ ] add to the post meta spec a param that allows matching to be displayed for certain keys
- [ ] create a separate field that combines content and specific post meta (maybe we display other matches also?)
- [ ] switch over to this new field for doing the highlighting

**Comment by gibrown** [comment]
When we highlight across multiple paragraphs or sections of content I think we should add some ellipsis between the content so that it spaces the content out better. An example from en.support.wordpress.com:

![screenshot-on-2020-06-12-at-12_39_44](https://user-images.githubusercontent.com/820871/84522459-e9beff80-ac93-11ea-9da0-bb11d6bfa10e.png)

Here the highlighting is coming from the table of contents, but there is no spacing between the items in the ToC which makes it tougher to read.

**Comment by gibrown** [comment]
It looks like we have some encoding issues when we fall back to the paths that we display. This is from ru.forums.wordpress.com:
<img width="1129" alt="Screen Shot 2020-06-12 at 12 56 21 PM" src="https://user-images.githubusercontent.com/820871/84537079-4e865400-acac-11ea-9f61-3f353d3c61cd.png">

**Comment by gibrown** [comment]
Some more ideas for better snippets and context:
- Have each highlighted snippet link to the post and scroll to where the matching content is located on the page. Implementation idea:
 - A link with a parameter containing the text.
 - Some JS on every page that looks for that param, scrolls the page, and highlights it to the user.
- Each comment can link to the appropriate comment.
- Select the best image to display that best matches the term. e.g. if a caption matches or the image is closer to things that match.
- Link directly to pdfs and other attached documents
- Parse Gutenberg and display blocks rather than just text. e.g. show a table in the results. Show multiple images if captions match.
- Expand the content of the post directly in place. e.g. show 3 matches by default, but have a button to expand to show more matches.
