### ISSUE TITLE
Instagram Gallery Block: Visual Attributes Jankiness

### ISSUE THREAD

**Issue by Copons** [Automattic/jetpack#15277]
See original discussion at https://github.com/Automattic/jetpack/pull/15091#issuecomment-608375862

- [x] Fade image placeholders - #15329
- [ ] ~~Improve sliders UX~~. debouncing removed in #15329 so not needed
- [ ] ~~Resettable settings~~ - decision made in #15438 to omit reset buttons for now.

### Images Placeholders Animation

In #15091 I've added some "pulsating" placeholders when waiting to receive the actual photos from the Instagram API.

Once the images arrive, the placeholder disappear at once, before the images are rendered.
This looks very janky!

![Apr-03-2020 12-09-23](https://user-images.githubusercontent.com/275961/78354594-0eb43980-75a4-11ea-8705-2c2d588cb351.gif)

### Sliders UX

~~The "Number of Posts" setting is debounced (as it triggers API calls), and so it looks like the change happens "on slider release".~~
~~The "Number of Columns" and "Image Spacing" settings are not debounced, ans so it looks like the changes happen immediately "on slider drag".~~

~~Should we make the experience consistent across the three sliders?~~

In #15329 we have moved to loading all 30 images up front so the debounce could be removed which made the behaviour of all the sliders the same.

### Resettable settings

Make the three attributes resettable.
