### ISSUE TITLE
WordPress 5.5 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15388]
For reference, here is a list of the things we should work on to ensure full compatibility with the upcoming version of WordPress, 5.5:
https://make.wordpress.org/core/5-5/

Internal reference: 1151641796826042-as-1163587527622980

Items checked are not impacting us, or already handled.

- [x] Lazy Loading #12512 
- [x] Sitemaps https://make.wordpress.org/core/tag/xml-sitemaps/
- [x] Comments: comments created via the API should use the `comment` `comment_type` #15531 
- [x] SimplePie: ensure compatibility with Podcast player #15662 
- [x] Better site environment detection #11798 
- [ ] jQuery changes: https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/ #16715 #16409 
- [ ] Buttons: Update CSS styles for buttons with disabled state #16452 
- [x] Connection package: review and deprecate use of $HTTP_RAW_POST_DATA #16488 #16766 -- https://make.wordpress.org/core/2020/07/14/php-related-improvements-changes-wordpress-5-5-edition/
- [x] Ensure that Jetpack autoupdates play well with core autoupdates https://make.wordpress.org/core/2020/07/15/controlling-plugin-and-theme-auto-updates-ui-in-wordpress-5-5/ #16600 #16741
- [x] REST API Permission Callback changes #16539 
- [x] Comment black/whitelist changes. https://make.wordpress.org/core/2020/07/23/codebase-language-improvements-in-5-5/ #16569 #16568 
- [x] Themes: changes related to get_custom_logo() in WordPress 5.5 https://make.wordpress.org/core/2020/07/28/themes-changes-related-to-get_custom_logo-in-wordpress-5-5/
- [x] Comments: Changes to return values https://make.wordpress.org/core/2020/07/29/miscellaneous-developer-focused-changes-in-wordpress-5-5/ (may impact sync)
- [x] Miscellaneous Changes https://make.wordpress.org/core/2020/07/29/miscellaneous-developer-focused-changes-in-wordpress-5-5/

**Comment by kraftbj** [comment]
https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/

**Comment by kraftbj** [comment]
For Lazy Loading, we can let it ride for 8.8, since the two methods don't make anything worse to both be active at the same time, but we'll need to make some decisions about our lazy loading feature in the near future.

**Comment by jeherve** [comment]
@mdbitz If you get the chance, do you think you could look at the changes made [here](https://core.trac.wordpress.org/ticket/39732), and ensure they won't impact sync in a bad way?

Thank you!

**Comment by kraftbj** [comment]
For `HTTP_RAW_POST_DATA` #16766, no need to rush this for WP 5.5.

**Comment by kraftbj** [comment]
> @mdbitz If you get the chance, do you think you could look at the changes made [here](https://core.trac.wordpress.org/ticket/39732), and ensure they won't impact sync in a bad way?
> 
> Thank you!

In looking, Sync picks up when actions are fired. In looking at how we sync comments, we don't actually use the `edit_comment` hook. The inline comment mentions this is because the hook doesn't include the data, but looks like in WP 4.6 it was added...so probably can make the Sync code a little cleaner here, but I digress. We actually look at the action when the comment status is transitioned, which wouldn't fire either way if the return is false, 0, or `WP_Error`.

I think we're safe on this front.

**Comment by kraftbj** [comment]
>     * Miscellaneous Changes https://make.wordpress.org/core/2020/07/29/miscellaneous-developer-focused-changes-in-wordpress-5-5/

These all seem fine for us. Checking the various functions mentioned, none of usages appear to be impacted from what I could tell.

**Comment by kraftbj** [comment]
8.8.1 shipped with the auto-updating plugins compat.

**Comment by jeherve** [comment]
Closing this for now since every remaining issue is tracked.
