### ISSUE TITLE
Search: sync post-meta/taxonomy indexing list into jetpack and document process to expand it

### ISSUE THREAD

**Issue by gibrown** [Automattic/jetpack#15672]
We have a hard coded list of post meta fields and custom taxonomies that we put into the search index. That list is in class.jetpack-sync-module-search.php on wp.com. We need to:
- [ ] sync the list to jetpack and likely refactor it significantly
- [ ] use this list to filter what taxonomies are available in the UI 
- [ ] add the list of post meta keys that can be filtered on (see https://github.com/Automattic/jetpack/issues/8663)
- [ ] document and create examples of how to request adding post-meta/taxonomies to the list (probably on jetpack.com/support/search, but maybe also in the UI).

**Comment by gibrown** [comment]
Fixing this, may also fix https://github.com/Automattic/jpop-issues/issues/5294 or enable us to fix it.

**Comment by bluefuton** [comment]
@gibrown is this needed for the first release of Jetpack Search for Woo? What's the impact of leaving it out?
