### ISSUE TITLE
Image Compare Block: Master issue

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#15742]
- [ ] AMP support #15653 
- [ ] broken placeholder layout when not using the Gutenberg plugin #15737 
- [ ] add uploading progress indicators #15738 
- [ ] add option to edit / replace existing images #15739 
- [ ] add additional alignment options #15740 
- [ ] add extra image attributes #15741

**Comment by kraftbj** [comment]
@mkaz What's the plan for resolving these outstanding issues and resolve the bugs raised?
