### ISSUE TITLE
Admin Page: Move from i18n-calypso to Core functions to handle translations

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#16481]
We're aiming to move away from the `i18n-calypso` tooling to handle translations. Instead we'll rely on 2 things (see discussion in #13527 for more background):

- `@wordpress/i18n` for most translation work: `__`, `_n`, `_x`, and `sprintf`.
- `@wordpress/element` and its `createInterpolateElement` to handle React elements in strings.

#### Task list

- [x] Update to latest stable of @wordpress/element #16478 
- [x] Update all admin dashboard files (will break this down in multiple PRs)
    - [x] Part 1: At A Glance #13527
    - [x] Part 2: Components #16497 
    - [x] Part 3: Plans, My Plans, Discussion, Performance #16498 
    - [x] Part 4: Security, Privacy, Search #16502 
    - [x] Part 5: Setup wizard #16503 
    - [x] Part 6: Writing, Traffic, Sharing, State #16515 
    - [x] Part 7: left-overs #16535 
- [x] Update documentation #16526 
- [x] Add linting to catch any outliers. `@wordpress/eslint-plugin` and its `i18n` section may be of use. #16516 
- [x] Move away from `i18n-calypso`'s `numberFormat` -- See https://github.com/Automattic/jetpack/pull/13527#discussion_r327584763, #17357 
- [x] Move away from `i18n-calypso`'s `moment` -- See #16397, #17321, #17343. 
- [x] Remove `i18n-calypso` dependency -- #17522 
- [x] Remove unneeded custom translation handling #16518 
    - [x] Remove locale info from the `Initial_State` JSON that's loaded with the React app, now that it will be loaded by WordPress.
    - [x] Remove function used to build the above.
    - [x] Remove Gulp tasks used to 1) extract strings from the React codebase into a `_inc/jetpack-strings.php` file (`languages:extract`), and then 2) create .json files from the .po files we get from translate.wordpress.org (`languages:build`)
    - [x] Move to language packs for all translation handling in Jetpack. p9dueE-1D0-p2
- [x] Tweak webpack config so translator comments are not dropped when building our production build. #16549 https://github.com/Automattic/wp-calypso/pull/48920
- [x] Test changes on a live site pxLjZ-63R-p2 -- It works! 🎉 

#### Jetpack product discussion

* p1HpG7-99c-p2
