### ISSUE TITLE
WordPress 5.6 Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17064]
**[Development Cycle](https://make.wordpress.org/core/5-6/)**
- Beta 1: 20 October 2020
- Release: 8 December 2020

*******

- [x] Update tested up to, require WordPress 5.5, remove old code #17820 
- [x] Widget Visibility / Widgets: ensure compatibility with Gutenberg 8.9 #17062 
- [ ] jQuery deprecation issues: Slideshow, Stats, Calypsoify, Likes, Sharing, Presentions shortcode, Recipes shortcode, and more (#16715) https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/ https://make.wordpress.org/core/2020/11/05/updating-core-jquery-to-version-3-part-2/
- [x] To test: Site Health Check changes in 5.6 https://make.wordpress.org/core/2020/11/15/site-health-check-changes-in-5-6/
- [x] To test: editor styling changes that may impact our External Media extension https://make.wordpress.org/core/2020/11/18/editor-styling-changes-in-wordpress-5-6/
