### ISSUE TITLE
General: compatibility with PHP 8

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17166]
Let's keep an eye on the upcoming changes in PHP 8, to ensure that Jetpack will be fully compatible.

- [x] Add PHP 8 to Travis Matrix
- [x] Avoid required parameters after optional parameters in function/method signatures -- [reference](https://php.watch/versions/8.0/deprecate-required-param-after-optional) #17755 
- [x] All PHP Magic methods should be public #17200 
- [x] Add necessary parameter to `mktime()` #17199 
- [x] String modification errors #17628 
- [x] `method_exists` throws a `TypeError` when not using an object or string (example: #17725) 
- [x] Fatal on Modules page. #18053 

---------

Of note, this may be useful as a way to review the most relevant changes for us:
https://developer.yoast.com/blog/the-2020-wordpress-and-php-8-compatibility-report/

**Comment by anomiex** [comment]
Bumping to 9.3, although if something important turns up we can do a 9.2 point release.
