### ISSUE TITLE
Twenty Twenty One Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#17248]
[Twenty Twenty One](https://make.wordpress.org/core/2020/09/23/introducing-twenty-twenty-one/) is expected to ship with WordPress 5.6 at the end of the year. It is currently being developed here:
https://github.com/WordPress/twentytwentyone

In the past, and with previous default themes, we've added a number of compatibility files and functions to make sure new WordPress site owners had the best experience they could get when using the default theme and Jetpack. In practice, it meant adding the following:

- [ ] Add Infinite Scroll support and tweak CSS to make sure the IS buttons look good.
- [x] Tweak CSS for Sharing buttons / Likes / Related Posts #17889 
- [x] Alter Gallery widget default width.
- [x] Style all Jetpack widgets to match the style of the theme. #17889 
- [x] Add Content Options support #17951
- [x] Ensure that sharing buttons and Likes are not hooked into the excerpt when one is added to a post.

**Previous art on this**

- Twenty Twenty #13511 
- Twenty Nineteen https://github.com/Automattic/jetpack/blob/50fe8a75fd8cfaa2aad34228ca3f02bb7ec60077/modules/theme-tools/compat/twentynineteen.php

**Internal references**

- pNEWy-did-p2

**Comment by anomiex** [comment]
It seems nothing happened here in time for actual 9.2. If anything very urgent turns up we can still cherry pick, but at this point anything minor will probably have to wait for 9.3.

**Comment by jeherve** [comment]
We've just merged a first version of the compat files with only a tiny change (to fix the display of related posts).

Looking at pNEWy-dmT-p2 , it seems the Themes team will be looking at this later this week. We can ship iterations on the compat (such as Infinite Scroll and Content Options) in 9.3.

**Comment by scruffian** [comment]
I'm not sure we need to add anything for the gallery widget; it looks ok to me:

![Uploading Screenshot 2020-12-03 at 10.20.47.png…]()
