### ISSUE TITLE
WordPress 5.7 Compatibility: Primary issue

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#18842]
WordPress 5.7 is set to release on March 9, 2021:
https://make.wordpress.org/core/5-7/

We consequently need to ensure that Jetpack is fully compatible with this new release.

- [x] Update our "tested up to" version #18860 
- [x] Update the version of WordPress required for Jetpack from WP 5.5 to WP 5.6 #18860
- [x] Remove WP 5.5 backwards compatibility checks #18860

In addition to the above, we can follow the dev-notes that will drop here about the release:
https://make.wordpress.org/core/tag/dev-notes+5-7/

- [ ] Ensure SSO and Protect are compatible with the latest round of changes to the log in screen ([reference](https://make.wordpress.org/core/2021/02/16/login-registration-screens-changes-in-wordpress-5-7/))
- [x] Deprecations: Changes to Toolbar components ([Reference](https://make.wordpress.org/core/2020/11/18/changes-to-toolbar-components-in-wordpress-5-6/)) #18860 
- [x] Robots API: update Jetpack to use new API when necessary #18897 ([reference](https://make.wordpress.org/core/2021/02/19/robots-api-and-max-image-preview-directive-in-wordpress-5-7/))
- [ ] Miscellaneous changes ([reference](https://make.wordpress.org/core/2021/02/23/miscellaneous-developer-focused-changes-in-wordpress-5-7/))
- [x] Color changes ([reference](https://make.wordpress.org/core/2021/02/23/standardization-of-wp-admin-colors-in-wordpress-5-7/) and [ticket](https://core.trac.wordpress.org/ticket/49999)) #18916
- [ ] Ensure that Inner Blocks API changes do not break the Form block ([reference](https://make.wordpress.org/core/2021/02/23/inner-blocks-api-changes/))
- [x] Contact Form: Narrow Editing Window on WordPress 5.7 #18932 

******

**Extras**

- [ ] Blocks: switch away from __experimentalBlock to useBlockProps #18864
