### ISSUE TITLE
Site Editor Compatibility: Tracking issue for remaining fixes for Jetpack block FSE support

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19504]
Following on from 256-gh-Automattic/view-design

The following are outstanding issues required to address support for Jetpack blocks with the new full site editing / site editor feature in Gutenberg.

To test the new site editor, install the Gutenberg plugin in a local development environment and activate a block-based theme (e.g. tt1-blocks), or create a new testing site at: https://horizon.wordpress.com/new?flags=gutenboarding/site-editor. The site editor will then be available from the dashboard menu, or via `/wp-admin/admin.php?page=gutenberg-edit-site`.

Note that there is [a PR](https://github.com/WordPress/gutenberg/pull/30552) that's been merged in Gutenberg that fixes some block rendering issues in Jetpack blocks on the front end. Before working on the below issues, you'll probably want to make sure to run a development build of Gutenberg that includes the fix (remove `wpautop` when rendering FSE templates) in your local environment, so that you don't get caught by the already-fixed bug 🙂

### Jetpack block issues

* [x] [Instagram Gallery Block styling issues in editor](https://github.com/Automattic/jetpack/issues/19466) (@aaronrobertshaw) https://github.com/Automattic/jetpack/pull/19529
* [x] [Image Compare Block doesn't render interface in editor](https://github.com/Automattic/jetpack/issues/19465) (@glendaviesnz)
* [x] [Jetpack Button block styling, and blocks that depend on it](https://github.com/Automattic/jetpack/issues/19464) (@andrewserong) https://github.com/Automattic/jetpack/pull/19595
* [x] [Business Hours Block editor styling](https://github.com/Automattic/jetpack/issues/19463) (@ramonjd) https://github.com/Automattic/jetpack/pull/19532
* [x] [Contact Form Block styling issues](https://github.com/Automattic/jetpack/issues/19462) (@apeatling) https://github.com/Automattic/jetpack/pull/19527
* [x] [Related Posts Block — doesn't really work in an FSE context](https://github.com/Automattic/jetpack/issues/19448) (@stacimc)
* [x] [Mailchimp Block styling issues on the front end](https://github.com/Automattic/jetpack/issues/19481) (@stacimc)
* [x] [Map Block — doesn't render in the editor](https://github.com/Automattic/jetpack/issues/19482) (@glendaviesnz)
* [x] [Podcast Player Block issues in editor and front end view](https://github.com/Automattic/jetpack/issues/19483) @ramonjd https://github.com/Automattic/jetpack/pull/19578
* [x] [Repeat Visitor Block styling issues with radio button in editor UI](https://github.com/Automattic/jetpack/issues/19484) (@andrewserong)
* [x] [Revue Block styling issues on front end](https://github.com/Automattic/jetpack/issues/19485) @andrewserong (check it works okay once https://github.com/Automattic/jetpack/pull/19595 lands)
* [x] [Simple Payments (Pay with PayPal) block issues in editor and front end](https://github.com/Automattic/jetpack/issues/19486) (@apeatling)
* [x] [Slideshow block styling issues in editor](https://github.com/Automattic/jetpack/issues/19487) (@stacimc) [PR] (https://github.com/Automattic/jetpack/pull/19543)
* [x] [WhatsApp button block height issue](https://github.com/Automattic/jetpack/pull/19531) (@andrewserong) [PR](https://github.com/Automattic/jetpack/pull/19531)
* [x] [Premium content blocks: parent block selector button selects template part instead of container](https://github.com/Automattic/jetpack/pull/19717) @andrewserong [PR](https://github.com/Automattic/jetpack/pull/19717) 

### Related issues in other repos
* [x] [Event Timeline block doesn't use alignment in full site editor](https://github.com/Automattic/wp-calypso/issues/51802) (@ramonjd) https://github.com/Automattic/wp-calypso/pull/52008
* [x] [Event Countdown block title field overflowing container in Safari](https://github.com/Automattic/wp-calypso/pull/51967) (@andrewserong) [PR](https://github.com/Automattic/wp-calypso/pull/51967)
* [x] [Gutenberg: Emotion-based CSS-in-JS styles aren't loaded into the editor canvas](https://github.com/WordPress/gutenberg/issues/30553) @andrewserong — proposed workaround for ExternalLink ([PR](https://github.com/Automattic/jetpack/pull/19564))
  - Short-term fix for ExternalLink component merged in https://github.com/Automattic/jetpack/pull/19564
  - Long-term Gutenberg fix has been merged in (https://github.com/WordPress/gutenberg/pull/31010)
* [x] [Layout grid UI fix will land in Layout Grid 1.6](https://github.com/Automattic/block-experiments/pull/177) (and D59235-code)

**Comment by andrewserong** [comment]
All of the reported issues have now been closed out. I'm sure we'll find other FSE issues as we go, but for now, we can call this particular phase done.

Thanks for all the great work on this, everyone!
