### ISSUE TITLE
WordPress 5.8 Compatibility: Primary issue

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#19654]
WordPress 5.8 is set to release on July 20, 2021
https://make.wordpress.org/core/5-8/

We consequently need to ensure that Jetpack is fully compatible with this new release **by Jetpack 9.9, scheduled to be released in early July.**

*******

- [x] Update our "tested up to" version (#20040)
- [x] Update the version of WordPress required for Jetpack from WP 5.6 to WP 5.7 (#20040)
- [x] Remove Instagram core compat code (see #19736, done via #20040)
- [x] Remove WP 5.6 backwards compatibility checks
- [x] Photon: add WebP image format support ([reference](https://core.trac.wordpress.org/changeset/50810) / Internal reference: p3topS-Tn-p2 ) / [Core Dev Note](https://make.wordpress.org/core/2021/06/07/wordpress-5-8-adds-webp-support/)
- [x] Review codebase for all Photon usages that are limited to specific formats to include WebP once the above is done.
- [x] Blocks: bundle not compatible with WP 5.8 #20089
- [x] Ensure our blocks extending core blocks properly handle global settings that may disable blocks ([reference](https://riad.blog/2021/05/05/introduction-to-wordpresss-global-styles-and-global-settings/))
- [x] Remove usage of `__experimentalBlock` in favor of `useBlockProps` https://github.com/WordPress/gutenberg/pull/31419/ #18864 
- [x] Full Site Editing block compatibility #19504
- [x] Review Jetpack blocks in Widget Editor 275-gh-view-design
- [x] Review legacy widgets in block widget editor
    - [x] Search: Widget settings #20055
    - [x] Milestone Widget #20208
- [x] Widget Visibility with the new Block-based Widget Editor #20057
- [x] Update Unit Tests to detect new default install #20136 
- [x] Update Site Logo's as the format conflicts with Gutenberg's Site Logo block (FSE) (#20047)
- [x] `block_editor_settings` deprecated in favor of `block_editor_settings_all` https://core.trac.wordpress.org/ticket/52920 https://github.com/Automattic/jetpack/pull/20201
- [x] Full Site Editing Compatibility: Multiple Blocks - "This Block Has Encountered an Error..." #20184
- [ ] Editor: solve conflict between Jetpack blocks' @wordpress/editor` dependencies and Block-based Widgets Editor #20357 

In addition to the above, we can follow the dev-notes that will drop here about the release:
https://make.wordpress.org/core/tag/dev-notes+5-8

*******

Internal references:
- p9dueE-2WM-p2
- 1192874419362946-as-1200393427368072

For reference: prior art for WordPress 5.7 compat: #18842

**Comment by anomiex** [comment]
> * [ ]  Photon: add WebP image format support ([reference](https://core.trac.wordpress.org/changeset/50810) / Internal reference: p3topS-Tn-p2 )

Then possibly we should also go through looking for places that limit types to gif, jpg, and png and add webp. #19927 just added one, for example.

**Comment by jeherve** [comment]
Good call; I added a checkbox for that 👍

**Comment by simison** [comment]
Have you tested how Jetpack features work with the new Query block shipping in 5.8? Especially the follow/likes buttons in posts. More context at pbAok1-27g-p2#comment-4353

**Comment by jeherve** [comment]
> Have you tested how Jetpack features work with the new Query block shipping in 5.8?

Likes and Sharing buttons will not appear when using the Query block to display a list of posts. The solution here will be for us to develop a sharing block and a Like block:
- Sharing #19694
- Likes #19659 
 
Related posts (also hooked into `the_content`) can be handed using the existing Related Posts block.

**Comment by kraftbj** [comment]
Are we going to wait until after 5.8 ships to drop 5.6 compat?

**Comment by jeherve** [comment]
@kraftbj I was thinking we would drop it on July 6 (so 2 weeks before the WP 5.8 release), like we did in the last time around for WP 5.7. That would mean that for 2 weeks, Jetpack would only support the current version of WordPress, but this seemed acceptable to me the last time around, and this time too. What do you think?

**Comment by kraftbj** [comment]
That sounds great to me!

**Comment by sdixon194** [comment]
Moving this to 9.9.1

**Comment by samiff** [comment]
Per internal p3topS-Tn-p2#comment-3720 WebP support is now active, but minimally the Photon code will need to be updated to take advantage.
