### ISSUE TITLE
Sharing: create a "Sharing Buttons" block

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19694]
Related Epic: #31920

Related to #19659 (essentially the same task for the Like button feature)

This issue is to implement a simple MVP server side rendering block for the "Share this" feature that gets automatically appended to the end of post content. Ideally in full site editing, a user should be able to place this feature where they like within a template part.

As an example, the below screenshot is a mock up of moving out the Like button feature to a Footer template part. Here, it's clear that it would be good for the user to also be able to place the "Share this" feature elsewhere within the page:

![image](https://user-images.githubusercontent.com/14988353/116512626-ae5d0c00-a90b-11eb-8036-e0f6cda3b8b2.png)

## Tasks

* [x] Create a block for the Sharing feature (and come up with a clear name for it)
  * [x] In the editor, use a static approximation of the feature
  * [x] On the front end, add a server side render_block method that calls the existing `sharing_display` method
* [ ] If an FSE theme is active, prevent the automatic `sharing_display` from appending the "Share this" feature to post content (it's registered against [the_content filter here](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L21-L21), and the [logic lives here](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/sharedaddy/sharing-service.php#L700-L700) )
* [ ] Ensure the existing settings to hide the sharing feature on an individual post or globally, still applies to the block version

*******

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/34050
- [ ] https://github.com/Automattic/jetpack/pull/34085
- [ ] https://github.com/Automattic/jetpack/issues/34108
- [ ] https://github.com/Automattic/jetpack/issues/34115
- [ ] https://github.com/Automattic/jetpack/issues/34116
- [ ] https://github.com/Automattic/jetpack/issues/34324
- [ ] https://github.com/Automattic/jetpack/issues/34325
- [ ] https://github.com/Automattic/jetpack/issues/34326
- [ ] https://github.com/Automattic/jetpack/issues/34327
- [ ] https://github.com/Automattic/jetpack/issues/34521
- [ ] https://github.com/Automattic/jetpack/issues/34580
- [ ] https://github.com/Automattic/jetpack/issues/34581
- [ ] https://github.com/Automattic/jetpack/issues/34596
- [ ] https://github.com/Automattic/jetpack/issues/34726
- [ ] https://github.com/Automattic/jetpack/issues/35047
- [ ] https://github.com/Automattic/jetpack/issues/35141
- [ ] https://github.com/Automattic/jetpack/issues/35143
- [ ] https://github.com/Automattic/jetpack/pull/35267
- [ ] https://github.com/Automattic/jetpack/issues/34621
- [ ] https://github.com/Automattic/jetpack/issues/34575
- [ ] https://github.com/Automattic/jetpack/issues/35286
```

**Comment by lakellie** [comment]
Just noting that we had a user contact us requesting this functionality in 5648078-zen

**Comment by jeherve** [comment]
Also suggested in pdHDFB-m-p2

**Comment by thekingsprojects** [comment]
Had a user confused by the lack of sharing buttons in their Query Loop block, expecting them to be available there: 6169722-zen

**Comment by Aurorum** [comment]
Came up in 7148193-zen

**Comment by jeherve** [comment]
Marking this as done. We'll iterate on this block in #35993.
