### ISSUE TITLE
Jetpack Block PHP Fixture Tests: Tracking issue for blocks requiring server-side rendering tests

### ISSUE THREAD

**Issue by andrewserong** [Automattic/jetpack#19812]
In #19743 we introduced a server-side fixture test for the Business Hours block. The test grabs the serialized markup from the JS-based fixtures tests, and runs the markup through the block's server-side `render_block` function. If a fixture for the server rendering does not exist, one is created. If a fixture exists, then the output of the `render_block` function is compared against the `*.server-rendered.html` fixture.

In this way, we have a (hopefully) fairly simple way of adding tests for the server rendering of blocks, in addition to the existing fixture tests that cover the JS edit and save behaviour.

This tracking issue is to add in similar tests for all the other Jetpack blocks that use server rendering. As part of this task, it would be good to look at the approach in #19743 and see if any of it can be generalised in a useful way for other tests.

## Tasks

* [ ] See if the approach from #19743 can be generalised in a useful way into utility functions for these tests
* [ ] Ensure that deprecated markup is also picked up by these server-based tests. Deprecated markup that hasn't _yet_ been migrated to the current markup (E.g. an old blog post that a user hasn't gone back to edit) should also result in successful server rendering of the block.

## Blocks that could use tests for their server-side rendering

Note: I haven't included blocks that use a `render_block` function that only loads assets. Each of the below blocks alters rendered markup in some way, so would benefit from fixture tests.

Also some blocks might perform API requests or do other things that could make it harder to get them under test. In some cases maybe this is an opportunity to do some light refactoring. In others, perhaps we should park it until we need to make changes to the block further down the track.

* [x] `jetpack/business-hours`
* [ ] `jetpack/button`
* [ ] `jetpack/calendly` (include deprecations, could be a good one to start with)
* [ ] `jetpack/contact-form` and associated blocks (registered [here](https://github.com/Automattic/jetpack/blob/ef6364966f1d52285c9a111e010d2a9ee178567f/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L246-L246)
  * [ ] `jetpack/field-text`
  * [ ] `jetpack/field-name`
  * [ ] `jetpack/field-email`
  * [ ] `jetpack/field-url`
  * [ ] `jetpack/field-date`
  * [ ] `jetpack/field-telephone`
  * [ ] `jetpack/field-textarea`
  * [ ] `jetpack/field-checkbox`
  * [ ] `jetpack/field-checkbox-multiple`
  * [ ] `jetpack/field-radio`
  * [ ] `jetpack/field-select`
  * [ ] `jetpack/field-consent`
* [ ] `jetpack/contact-info` and associated blocks
  * [ ] `jetpack/address`
  * [ ] `jetpack/email`
  * [ ] `jetpack/phone`
* [ ] `jetpack/donations`
* [ ] `jetpack/eventbrite`
* [ ] `jetpack/gif`
* [ ] `jetpack/google-calendar`
* [ ] `jetpack/image-compared` (just for AMP support?)
* [ ] `jetpack/instagram-gallery`
* [ ] `jetpack/mailchimp`
* [ ] `jetpack/map` (inserts an API key, might need some mocking?)
* [ ] `jetpack/opentable`
* [ ] `jetpack/pinterest`
* [ ] `jetpack/podcast-player`
* [ ] `jetpack/premium-content`
* [ ] `jetpack/rating-star`
* [ ] `jetpack/recurring-payments`
* [ ] `jetpack/repeat-visitor`
* [ ] `jetpack/revue`
* [ ] `jetpack/simple-payments`
* [ ] `jetpack/slideshow`
* [ ] `jetpack/story`
* [ ] `jetpack/tiled-gallery`
* [ ] `jetpack/wordads`

Note: For the Jetpack Contact Form, [tests already exist](https://github.com/Automattic/jetpack/blob/5a27b8ae1a760c0098067ddc152ac0879b9a2a91/projects/plugins/jetpack/tests/php/modules/contact-form/test-class.grunion-contact-form.php) — before working on it, check to see whether or not the existing tests provide adequate coverage. We might not need to fixture tests for this one if the existing tests suffice.
