### ISSUE TITLE
WordPress 5.9 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#21322]
WordPress 5.9 is set to release on ~December 14, 2021~ January 25, 2022.
https://make.wordpress.org/core/5-9/

We consequently need to ensure that Jetpack is fully compatible with this new release ~by Jetpack 10.4, scheduled to be released in early December.~ by Jetpack 10.5, scheduled to be released in early January.

*******

- [x] Update our "tested up to" version #21788
- [x] Update the version of WordPress required for Jetpack from WP 5.7 to WP 5.8 #21788
- [x] Remove WP 5.7 backwards compatibility checks #21788
- [ ] Refactor Subscriptions block to not use a shortcode (#15227)
- [x] Twenty Twenty Two Compatibility #21449
- [x] Ensure Admin Bar is still functional after https://core.trac.wordpress.org/ticket/28569 lands. Open new issue if there are issues.
- [x] Sync / Themes: take advantage of new `delete_theme` and `deleted_theme` introduced in WP 5.8. #20261
- [x] FSE + Likes non-functional. Potentially a Core-side fix so need to watch https://core.trac.wordpress.org/ticket/54529
- [x] Test the new language switcher in Login screen and ensure it works well with Protect's Math Fallback as well as SSO. https://core.trac.wordpress.org/ticket/43700
- [x] Miscellaneous block editor changes https://make.wordpress.org/core/2022/01/04/miscellaneous-block-editor-changes-in-wordpress-5-9/
- [x] Miscellaneous Core changes in WordPress 5.9 https://make.wordpress.org/core/2022/01/04/miscellaneous-core-changes-in-wordpress-5-9/

In addition to the above, we can follow the dev-notes that will drop here about the release:
https://make.wordpress.org/core/tag/dev-notes+5-9

*******

For reference: prior art for WordPress 5.8 compat: #19654

**Comment by jeherve** [comment]
> Ensure Admin Bar is still functional after core.trac.wordpress.org/ticket/28569 lands. Open new issue if there are issues.

This seems it will not land in this release:

> Moving to Future Release until the patch is refreshed, with unit tests.

**Comment by kraftbj** [comment]
5.9 delayed. https://make.wordpress.org/core/2021/11/17/wordpress-5-9-beta-1-delayed/
