### ISSUE TITLE
My Jetpack MVP: Overview

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#22285]
Jetpack has been split into more than one plugin. Paid features are now shipped as standalone plugins. [Jetpack Backup](https://href.li/?https://wordpress.org/plugins/jetpack-backup), [Jetpack Boost](https://href.li/?https://wordpress.org/plugins/jetpack-boost/), and more will come.

It is necessary to be consistent across different plugins when showing the user the state of their Jetpack account, their plan or the status of their Jetpack connection in wp-admin. Multiple plugins can be installed on a given site as well as the main Jetpack plugin.

[Progress Board](https://github.com/Automattic/jetpack/projects/36)

![image](https://user-images.githubusercontent.com/746152/149356765-f5bde627-d851-4097-8c38-7a5ab4c9db1a.png)

## Goal

The goal of the My Jetpack package is to provide an admin page consumable by all Jetpack plugins. This admin page would offer users a consistent admin interface across different products with an accurate map of active Jetpack features on the site in spite of the presence or absence of any given Jetpack feature plugin.

## Challenges

We should be able to ship the My Jetpack admin page on Jetpack plugins without adding much completity to those plugins. This will be hard but it's the main goal of the My Jetpack package. For this we'll be validating integration against the Jetpack Backup plugin.

* For internal reference on My Jetpack please refer to the Project Thread post p9dueE-3Xz-p2
  For context check the post's section **Resources**

#### Critical dates

**February 15th**: Things should probably work fine by this date.
**February 22nd**: Release date for Jetpack 10.7 beta
**March 1st**: Jetpack 10.7 release

## Tasks

The main objective is to build the **Sections** of the Overview page and achieve the **Flows**.

We should focus on just the “overview” page. No extra pages or views, tabs, or menu. This should allow to start testing out hypothesis and get feedback from users.

### General tasks

- [x] #21464
- [x] #21826
- [x] #21938
- [x] #22009
- [x] #22302
- [x] #22334
- [x] #22362
- [x] #22406
- [x] #22367
- [x] #22466
- [x] #22477
- [x] #22481

#### Product Cards section

- [x] #22286
- [x] #22287
- [x] ~#22292~
- [x] ~#22293~
- [x] #22463 
- [x] #22406
- [x] #22477

#### Plans section

- [x] #22288
- [x] #22289
- [x] #22290
- [x] #22330
- [x] #22386

#### Connections section

- [x] #22067
- [x] #22141
- [x] #22180
- [x] #22291
- [x] #22346
- [x] #22355

#### Global error notices

- [x] #22484

#### Flow for Adding products

Two variations of this flow have been considered: One flow for paid products and another for free products. Both of these assume we can side-load plugins.

- [x] Create interstitial pages
  - [x] https://github.com/Automattic/jetpack/pull/22593
- [x] Figure out if we needs routes?
  - [x] Add Tracks to them
    - [x] https://github.com/Automattic/jetpack/pull/22663
    - [x] https://github.com/Automattic/jetpack/pull/22672 
  - [x] Investigate PR https://github.com/Automattic/jetpack/pull/21196 as previous work. Let's not put it into components. Better to copy an improve inside my-jetpack
  - [x] Add endpoint for fetching products (we get prices and discount here. We may need to hardcode this. See https://github.com/Automattic/jetpack/blob/a30164a251520592a8bf8809a0b2b588ed464fd2/projects/plugins/jetpack/_inc/client/state/initial-state/reducer.js#L525 and [get_products_for_purchase()](https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/class.jetpack.php#L7128)
  - [x] Create interstitial for Boost
    - [x] https://github.com/Automattic/jetpack/pull/22643
    - [x] https://github.com/Automattic/jetpack/pull/22656
    - [x]  https://github.com/Automattic/jetpack/pull/22680
  - [x] https://github.com/Automattic/jetpack/pull/22687
    - [x]  Use proper pricing
  - [x] Create interstitial for Backup
    - [x]  Use proper pricing
#### Flow for Deactivating products

We’re allowing customers to deactivate products on this page but they cannot actually remove a product — they would still rely on the plugins view for that

#### Flow on Global Error & Fixing missing user connection

We  show how someone would still be able to access the My Jetpack page, even without a user connection. It also shows a global error letting them know about this missing connection.

#### Flow for Disconnecting Jetpack

This is similar to the _Flow for Deactivating products_ from above but for the Jetpack connection: it uses the same modal, the same content, but changes verbiage slightly. On the last step it also shows how Jetpack would behave with just an individual product that is inactive.

## Smoke Testing <a href="#smoke-testing" id="smoke-testing">#</a>

* Launch a Jurassic Ninja site with Jetpack Backup running its bleeding Edge version: 

https://jurassic.ninja/create/?jetpack-beta&my-jetpack&branches.jetpack-backup=master

* Connect the site via the Jetpack Backup plugin
  ![image](https://user-images.githubusercontent.com/746152/148967361-0784fce2-0a04-46d8-a166-d664e227ce56.png)

* Confirm that you see a new menu item under Jetpack: My Jetpack, and that by visiting it, you see the state of your connection:

  ![image](https://user-images.githubusercontent.com/746152/148967575-27d926ac-83ce-4c4b-8322-620f1b4c41d5.png)
