### ISSUE TITLE
My Jetpack: Update `<ConnectionScreen />` layout to match Figma

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#22649]
We need to update our `ConnectionScreen` to match the expected one:

![image](https://user-images.githubusercontent.com/1663717/152421907-ce2b0ea0-cf5e-4723-b137-de07d2753303.png)

Currently, it has some differences:

- [x] Button is `blue` (needs to be made in `ConnectScreen` on `connection` js-package). ( #22966 )
- [x] `X` button not implemented. ( #22983 )
- [ ] Footer doesn't have `Wordpress.com` | `Google` | `Apple` icons. ( #23036 )
- [ ] Missing `See all Jetpack features` list ( #23223 )
