### ISSUE TITLE
WordPress 6.0 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#24082]
WordPress 6.0 is set to release on May 24, 2022.
https://make.wordpress.org/core/6-0/

We consequently need to ensure that Jetpack is fully compatible with this new release by Jetpack 10.9, scheduled to be released in early May.

**If not possible, maybe we could push a new release a few days before May 24, maybe the week before on May 17?**

@kraftbj What's your take on this?

*******

- [x] Update our "tested up to" version #24083
- [x] Update the version of WordPress required for Jetpack from WP 5.8 to WP 5.9  #24083
- [x] Remove WP 5.8 backwards compatibility checks #24086
- [x] #24224
- [x] [Block Editor miscellaneous Dev Notes for WordPress 6.0](https://make.wordpress.org/core/2022/05/03/block-editor-miscellaneous-dev-notes-for-wordpress-6-0/)
- [x] [Miscellaneous Dev Notes for WordPress 6.0](https://make.wordpress.org/core/2022/05/03/miscellaneous-dev-notes-for-wordpress-6-0/)

In addition to the above, we can follow the dev-notes that will drop here about the release:
https://make.wordpress.org/core/tag/dev-notes+6-0

*******

For reference: prior art for WordPress 5.9 compat: #21322
Internal: p9dueE-4XE-p2

**Comment by kraftbj** [comment]
> If not possible, maybe we could push a new release a few days before May 24, maybe the week before on May 17?

I fully support a release out of cycle if there's anything critical to ensure compatibility. I think we can treat it as a point release (cherry-picking anything needed for compact). With it being a late-in-the-month release and the majority of the field notes for 6.0 not published, I don't think we should push ourselves to make 10.9 deemed compat.

**Comment by kraftbj** [comment]
Noting that we updated Sync to work with a change in WP 6.0. That was reported upstream and resolved. We don't need to revert our change, but previous versions of Jetpack should not be impacted (assuming a second committer approves to cherry pick the changeset to the 6.0 branch)

https://core.trac.wordpress.org/changeset/53362
