### ISSUE TITLE
Unable to connect to Instagram or Facebook via Publicize

### ISSUE THREAD

**Issue by galakhyati** [Automattic/jetpack#24907]
## *UPDATE*
**_This issue should now be resolved.  pbg9X-hnZ-p2_**

Previously connected sites, that have not attempted to reconnect, should be working as expected.

Sites that attempted to reconnect during the outage may need to perform another reconnect.

---

### Quick summary

The user had Instagram connected to their site by showing it on the Latest Instagram Post block on their homepage in the footer. The block was showing this error: `An error occurred. Please try again later.`

When checking under My Site → Tools → Marketing → Connections, there it is prompting `There is an issue connecting to Instagram`. When I try to disconnect and try to reconnect I'm facing the message as: 

{"error_type": "OAuthException", "code": 400, "error_message": "Insufficient developer role"}

The user reported the issue, and I'm able to replicate the issue.

For my connected Facebook connection, it shows there is some issue and it needs to reconnect.

### Steps to reproduce

1. Have a site where you have a connection to Instagram.
2. Go to My Site → Tools → Marketing → Connections
3. You shall see there is a notice to reconnect
4. Disconnect the connection
5. Try to reconnect. You shall see the error message.

### What you expected to happen

The connection to work without needing to reconnect. And even if I had to connect it should allow to connect without any error.

### What actually happened

Saw an error on reconnecting to Instagram

### Context

Customer report
Chat: 35942434-hc
Follow up ticket: 5337548-zd-woothemes
Slack: p1656566308210459-slack-C03TY6J1A
Reported to dotcom-escalation: p1656569211672339-slack-C02FMH4G8

### Simple, Atomic or both?

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

**Comment by rinazrina** [comment]
Another report: 29963214-hc

- [x] follow-up: 5337626-zd-woothemes

The user is getting the same error as @galakhyati mentioned above when connecting to Instagram. 

When connecting to Facebook, they're getting the following error message: 

`App Not Setup
This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.`

Tried with Edge and Chrome.

**Comment by devNigel** [comment]
Another report:

- [x] User report and ticket: 5337481-zd-woothemes

They reported this: 

> I keep getting a message that it is still in development mode and I don't have access to it.

**Comment by devNigel** [comment]
Another report:

- [x] User report and ticket: 5337538-zd-woothemes

**Comment by vajrasar** [comment]
Another

28998487-hc 

- [x] FollowUp 5337868-zd-woothemes

**Comment by inaikem** [comment]
Internal discussion here: p1656569211672339-slack-C02FMH4G8

Moving to the JP repo.

Cc @pablinos, @kristinaplauche

**Comment by edwinho89** [comment]
- [x] 5337881-zd-woothemes

User shared concerns where older publicized posts have been removed by Facebook automatically. Reviewing (_edited_) the Publicize report card, we can see they were successful, however removed in the FB page https://www.facebook.com/nuakhblog

**Comment by vajrasar** [comment]
> * [x]  5337881-zd-woothemes
> 
> User shared concerns where older publicized posts have been removed by Facebook automatically. Reviewing (_edited_) the Publicize report card, we can see they were successful, however removed in the FB page https://www.facebook.com/nuakhblog

@edwinho89 can you please try to replicate the "older publicized posts have been removed by Facebook automatically" aspect of this case? This could be related to this report but have not been reported so far.

**Comment by danielk-am** [comment]
Encountered here - 35211283-hc

- [x] Follow-up - 5337611-zd-woothemes

With the following error message when attempting to connect to Facebook:

```
App not set up
This app is still in development mode, and you don’t have access to it. Switch to a registered test user or ask an app admin for permissions.
```

**Comment by donalirl** [comment]
Encountered in #35489901-hc

- [x] Follow-up: #5337937-zen

**Comment by csabarakasz** [comment]
Same here: 
![fgSMbx](https://user-images.githubusercontent.com/84539773/176638485-87671c19-fe9f-40cd-990f-508fd29c9925.png)

Encountered: 33372244-hc

Follow up:
- [x] 5337935-zd-woothemes

**Comment by sharonlaker19** [comment]
+1 in 28468163-hc

- [x] Follow up here 5337740-zen

They also mentioned:

> all my previously shared posts have disappeared from FB.

**Comment by donalirl** [comment]
Encountered in #35232091-hc

- [x] Follow-up: #5337947-zen

**Comment by dragstor** [comment]
23919698-HC

- [x] Follow-up: 5337965-ZD

**Comment by kingsleyinfo** [comment]
26839847-HC

- [x] Follow-up: 5337974-ZD

**Comment by foleynotrose** [comment]
5337951-zd-woothemes

**Comment by KokkieH** [comment]
Two so far on wpcom forums:

* https://wordpress.com/forums/topic/all-my-facebook-posts-have-disappeared/?view=all
* https://wordpress.com/forums/topic/reconnecting-facebook-2/?view=all

**Comment by kdevnel** [comment]
35795085-hc

- [x] Follow-up: 5338032-zd-woothemes

**Comment by donalirl** [comment]
#35363899-hc

- [x] Follow-up: #5338061-zen

**Comment by foleynotrose** [comment]
5337996-zd-woothemes

**Comment by kingsleyinfo** [comment]
More reports below!

35944374-hc

- [x] Follow-up: 5338069-zd

30859249-hc

- [x] Follow-up: 5338076-zd

27988770-hc

- [x] Follow-up: 5338371-zd

35945417-hc

- [x] Follow-up: 5338571-zd

35133051-hc

- [x] Follow-up: 5338490-zd

**Comment by DavidSaladu** [comment]
More reports:
18827546-HC
5337558-zd-woothemes 
5338545-zd-woothemes 

I will add mine on this post to not post a lot of times.

**Comment by KokkieH** [comment]
@vajrasar 

> can you please try to replicate the "older publicized posts have been removed by Facebook automatically" aspect of this case? This could be related to this report but have not been reported so far.

I can confirm this. I have a Facebook page for my blog at https://www.facebook.com/useahammer, and almost every post on my site has been shared there for years. But now it's not showing anything after August 2016 - all posts I've shared via Publicize since then has disappeared from my Facebook page.

**Comment by annbingle** [comment]
Same issue reported here: 35587372-hc

- [x] Follow-up: 5338097-zen

**Comment by annbingle** [comment]
Same issue reported here: 31976194-hc

- [x] Follow-up: 5337864-zd

**Comment by filipanoscampos** [comment]
Reported here 5338106-zd-woothemes

- [x] Please follow-up here 5338106-zd-woothemes

**Comment by silvio-meter** [comment]
Same issue reported here: 33988804-hc
Follow-up: 5338182-zd-woothemes

**Comment by rakshitwesley** [comment]
Same issue: 35944278-hc

**Comment by nagpai** [comment]
Reported here 35657095-hc

- [x] Followup - 5338198-zd-woothemes

**Comment by galakhyati** [comment]
Reported here: 35935473-hc

- [x] Follow up: 5338169-zd-woothemes

**Comment by nagpai** [comment]
Reported here 35944856-hc

- [x] Followup - [5338200-zd](5338200-zd-woothemes)
User reports existing posts on Facebook page added via publicize also disappeared.

**Comment by brinbliss** [comment]
Reported here: hc-35278547

- [x]  Follow-up opened here: 5338284-zd-woothemes

This user sees a specific message, "App not created", when attempting to share via Facebook.

**Comment by sudeepbaral** [comment]
Another report here: 5338106-zd

Apart from the Facebook connection issue, the user's old posts shared using Publicize are deleted as well. The user shared the following:

`Every post which was shared to Facebook since we started using the option to directly share through Wordpress has been deleted from the facebook page. Hundreds and hundreds of posts are gone. This is a major issue which will have a direct financial impact on us. We will work manually for now but the biggest issue is the old posts being gone. That’s the issue we really need to resolve. `

**Comment by rakshitwesley** [comment]
Issue: 35945184-hc

Followup: 5338351-zd-woothemes

**Comment by sudeepbaral** [comment]
Reported here: 31741968-hc

Followup: 5337521-zen

The user initially contacted us about old posts shared using Publicize disappearing from Facebook. The user is seeing the following error when reconnecting Facebook:

`{"error_type": "OAuthException", "code": 400, "error_message": "Insufficient developer role"}`

**Comment by annbingle** [comment]
Same issue reported here: 28808917-hc

- [x] Follow-up: 5338361-zd

**Comment by StefMattana** [comment]
One Instagram Widget forum report here: https://wordpress.org/support/topic/instagram-connectivity/

**Comment by mihpaese** [comment]
Forum tickets:
- https://wordpress.org/support/topic/instagram-connectivity/#post-15784903
- https://wordpress.org/support/topic/wrong-share-count-on-home-page/#post-15784901

**Comment by rinazrina** [comment]
Another one: 

- [x] 5338331-zd-woothemes

**Comment by filipanoscampos** [comment]
Another case here35788992-hc

Please follow-up:

- [x] 5338412-zd-woothemes

**Comment by csabarakasz** [comment]
- [x] 5338504-zd-woothemes

:)

**Comment by ukheather** [comment]
Same issue here.

Had facebook connected for years via jetpack. I found out it hadn't been working not that it told me.
Now get 2 errors when trying to connect it again. It won't connect no matter the browser or how you try such as via your own site or via jetpack.com

The not set up error ALWAYS pops up no matter how you do it, the other error only when using jetpack.com trying to set facebook up

**Error message 1:**
![image](https://user-images.githubusercontent.com/32431390/176680735-371b5e0c-f009-45d6-9294-939d6ad26e3b.png)

**Error message 2:**
![image](https://user-images.githubusercontent.com/32431390/176680788-3bc88371-6e19-4631-be49-1e463db12978.png)

**Comment by sophiegyo** [comment]
1. Interaction/user report: 32263945-hc
Follow-up created:  
- [x] 5338508-zen

2. Interaction: 17626399-hc
Follow-up created:  
- [x] 5338587-zen

**Comment by dragstor** [comment]
Interaction: 35945805-HC

The user says their Instagram widget works fine.

- [x] 5338574-zen

**Comment by fetenlakhal** [comment]
- [x] 5337930-hc

**Comment by mihpaese** [comment]
- [ ] 5338433-zen
- [ ] 5338030-zen
- [ ] 5338454-zen

**Comment by ClassicRKR27** [comment]
Another report here: 35636604-hc

- [x] Follow-up ticket: 5338657-zd-woothemes

**Comment by fetenlakhal** [comment]
- [x] 5338658-hc

**Comment by upwardmomentum84** [comment]
Another report: 

- [x] 6911603-hc

**Comment by aleone89** [comment]
Follow ups needed for: 

- [x] 16534224-hc
- [x] 35946162-hc
- [x] 35946073-hc

**Comment by marcuswisecaesar** [comment]
Another report here: 35946320-hc

- [x] Follow-up ticket: 5338771-zd-woothemes

**Comment by tvolpert** [comment]
Reported here: 34130166-hc

- [x] followup ticket: 5338776-zd-woothemes

**Comment by liviopv** [comment]
- [x] 5338781-zd-woothemes
- [x] 5338798-zd-woothemes

**Comment by Joshgrygiel** [comment]
- [x] Another: 5338787-zen

**Comment by brinbliss** [comment]
Reported here: hc-35946466

- [x] : 5338811-zd-woothemes

**Comment by ghost** [comment]
- [x] Another: 5337690-zen

**Comment by JoshuaGoode** [comment]
**UPDATE:**

This issue should now be resolved.

Previously connected sites, that have not attempted to reconnect, should be working as expected.

Sites that attempted to reconnect during the outage may need to perform another reconnect. 

re: pbg9X-hnZ-p2

**Comment by bobmatyas** [comment]
- [ ] Another report here: 5338760-zd-woothemes

**Comment by julsyd** [comment]
It seems a list of Jetpack tickets was also created [in a separate issue](https://github.com/Automattic/jpop-issues/issues/7547). I've copied them below:

- [x] 5337571-zen
- [x] 5337739-zen
- [x] 5337801-zen
- [x] https://wordpress.org/support/topic/cant-connect-facebook-page-with-publicize-connections
- [x] 5338143-zen
- [x] 5338275-zen
- [x] 5338495-zen
- [x] 5338717-zen
- [x] 5337950-zen
- [x] 5338051-zen
- [x] 5338220-zen
- [x] 5338370-zen
- [x] 5338399-zen
- [x] 5338515-zen
- [x] 5338687-zen
- [x] 5338743-zen
- [x] 5338734-zen

**Comment by vajrasar** [comment]
Hi everyone 👋 Just a quick note to let you all know @Automattic/dotcom-triage-pa-group has finished following up with the affected WPCOM users reported in this thread.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.

**Comment by bobmatyas** [comment]
Jetpack users have been responded to via 7547-gh-Automattic/jpop-issues
