### ISSUE TITLE
Google Docs Embed Block: Primary issue

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#25344]
- [ ] Ensure private preview notice works well with dark themes https://github.com/Automattic/jetpack/pull/24628#pullrequestreview-1041412672
- [ ] Switch to `@automattic/jetpack-base-style` https://github.com/Automattic/jetpack/pull/24628#discussion_r920868643
- [ ] Ensure labels can be translated https://github.com/Automattic/jetpack/pull/24628#discussion_r934321936
- [ ] Add tests for the block. See other blocks (e.g. Subscriptions) for some examples.
- [ ] Add test for `map_gsuite_url` https://github.com/Automattic/jetpack/pull/24628#discussion_r934328642

********

Internal references:
- pdqkMK-ch-p2 
- Previous art on P2s: 2485-gh-p2

********

cc @gthayer

**Comment by jeherve** [comment]
@that-mike-bal Feel free to edit the issue above and add to the list if you have more items you'd like to address.
