### ISSUE TITLE
WordPress 6.1 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#25417]
WordPress 6.1 is set to release on November 1, 2022.
https://make.wordpress.org/core/6-1/

We consequently need to ensure that Jetpack is fully compatible with this new release by Jetpack 11.5, scheduled to be released on November 1, or maybe even 11.4, in October (we usually avoid releasing a version of Jetpack on the same day as a new version of Core).

*******

- [x] Update our "tested up to" version: https://github.com/Automattic/jetpack/pull/27084 
- [x] Update the version of WordPress required for Jetpack from WP 5.9 to WP 6.0: https://github.com/Automattic/jetpack/pull/27084
- [x] Remove WP 5.9 backwards compatibility checks: https://github.com/Automattic/jetpack/pull/27084
- [ ] Ensure compatibility with new resource preloading features #25416
- [x] Ensure compatibility with new default theme, Twenty Twenty Three
    In the past, and with previous default themes, we've added a number of compatibility files and functions to make sure new WordPress site owners had the best experience they could get when using the default theme and Jetpack. In practice and for a block theme like Twenty Twenty Three, it means adding at least the following:
    - ~[ ]  Tweak CSS for Sharing buttons / Likes / Related Posts~ ([see below comment](https://github.com/Automattic/jetpack/issues/25417#issuecomment-1292202609))
- [x] ~Ensure that all our features (notably OG tags, Subscription emails, Publicize and Publicize to Twitter Threads, features that use image extraction from `Jetpack_PostImages` continue to work well with the new WebP options enabled in Core. ([ticket](https://core.trac.wordpress.org/ticket/55443))~ ([see below comment](https://github.com/Automattic/jetpack/issues/25417#issuecomment-1285894839))

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-1](https://make.wordpress.org/core/tag/dev-notes+6-1)

*******

For reference: prior art for WordPress 6.0 compat: #24082

**Comment by bindlegirl** [comment]
The WebP issue was moved to Future release and removed from 6.1 milestone

**Comment by coder-karen** [comment]
> Ensure compatibility with new default theme, Twenty Twenty Three
>  Tweak CSS for Sharing buttons / Likes / Related Posts

Nothing needed here from my testing. Also, following the similar suggestions and info in the [Twenty Twenty Two issue](https://github.com/Automattic/jetpack/issues/21449) - nothing else looks to be needed for theme compatibility.

**Comment by coder-karen** [comment]
> Ensure compatibility with new resource preloading features https://github.com/Automattic/jetpack/issues/25416

This is the only compatibility check not yet looked at. It is a good-to-have (not breaking), so ideally we can follow up as soon as possible.
