### ISSUE TITLE
My Jetpack Connection management enhancements: Overview

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#26577]
A connection owner (primary admin) cannot currently access the connection ownership transfer functionality from within My Jetpack. All they can do is disconnect.

This would amend the disconnection flow to include an option for either disconnection or ownership transfer of the connection. 

P2 design and discussion:
Designs: p1HpG7-hKa-p2
Based on explorations in p1HpG7-1A6-p2 

![Manage options](https://user-images.githubusercontent.com/16329583/193575882-445513da-1ea1-4421-bcb5-71d8766c88da.png)

### Goals
* Allow connection owners to transfer the connection ownership to other admins of the site
* Create a path to get to the ownership transfer functionality that currently exists on wordpress.com

### Tasks:
- [x] Create new dialog component ( and story ) in connection to display transfer and disconnect options -> done in #26597 
- [x] Add wcpom redirect functionality -> Done in #26700 
- [x] Add disconnect Jetpack functionality to the modal
- [x] Add styling to the component
- [x] Activate modal changes and Modify My Jetpack UI to show 'manage connection' instead of 'disconnect'
