### ISSUE TITLE
VideoPress: handle isPrivate flag correctly when deciding if a thumbnail is private

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#26938]
The video privacy setting inside the VideoPress library allows 3 values:

1. public
1. private
1. same as site

1 and 2 are intuitive. The third value informs that the video privacy should follow the site settings. This setting is defined inside `Jetpack > Settings`, on the `Performance` tab:

![image](https://user-images.githubusercontent.com/6760046/196766083-d20e9aef-aed3-435d-95b7-7b9a4c12d9d8.png)

The setting is only available when the Jetpack plugin is active.

We need to make sure the changes made to acomodate private thumbnails also include a check on this additional flag.

### Tasks

- [x] Frontend: Implement the UI (https://github.com/Automattic/jetpack/pull/27290)
- [x] Backend: get/update the site option (https://github.com/Automattic/jetpack/pull/27293)
- [x] Data Handling: Connect the backend with front-end by hitting an endpoint
   - [x] use selector&resolver to get the current value for the privacy setting (#27321)
   - [x] connect the current value to the UI component (https://github.com/Automattic/jetpack/pull/27350)
   - [x] update the value on the backend when the value of the component changes using the API (https://github.com/Automattic/jetpack/pull/27350)

**Comment by retrofox** [comment]
We need to implement the same option but in the VideoPress dashboard, I guess.

**Comment by retrofox** [comment]
Slack thread: p1666790178639289-slack-C03TA48NSUX

**Comment by retrofox** [comment]
![Image](https://user-images.githubusercontent.com/77539/198097122-7f1efefb-3708-43c3-8701-93adc7b12026.png)

**Comment by retrofox** [comment]
@lhkowalski would you mind doing the backend part? Basically, we need to store the video-privacy flag somewhere 😅

**Comment by lhkowalski** [comment]
I will take part of the work on the data handling task, because I need to make the site privacy information available on the client to be able to solve #27314.

What I will start doing is the resolver and selector part, as well as probably the backend initial state. With this, I work on the private site thumbnail issue and we can move the feature of this issue forward.
   * PR: #27321

**Comment by lhkowalski** [comment]
Regarding this:

> We need to make sure the changes made to acomodate private thumbnails also include a check on this additional flag.

I am tackling it on #27314, because to solve the issue we need to take this new flag into account.

**Comment by retrofox** [comment]
> I am tackling it on #27314, because to solve the issue we need to take this new flag into account.

Reopening...
