### ISSUE TITLE
WordPress 6.2 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#27795]
WordPress 6.2 is set to release on March 28, 2023.

- Planning: [make.wordpress.org/core/6-2](https://make.wordpress.org/core/6-2/)

Let's use this issue to keep track of anything that may come up until then.

- [x] Update our "tested up to" version to 6.2 -> #29341
- [x] Update the version of WordPress required for Jetpack from WP 6.0 to WP 6.1:  **On hold for now, see p9dueE-6vE-p2#comment-9128**
- [x] Remove 6.0 backward-compatible checks **On hold for now, see p9dueE-6vE-p2#comment-9128**
- [ ] Non-plain-text block description is being deprecated in WordPress 6.2 #26792
    - Discussion is still ongoing on the better solution for this (see #26792). #29757 is the PR that would just remove the deprecation notices, if we decide to go with that.
- [x] Blocks: remove deprecated selector #28719 
- [x] `get_page_by_title` is now deprecated ([source](https://make.wordpress.org/core/2023/03/06/get_page_by_title-deprecated/))
- [x] Deprecating bottom margin on control components ([source](https://make.wordpress.org/core/2023/03/03/editor-components-updates-in-wordpress-6-2/))
- [x] Changes to inline styles for `InputControl` and `UnitControl` ([source](https://make.wordpress.org/core/2023/03/03/editor-components-updates-in-wordpress-6-2/)) (in VideoPress)
- [x] `position` prop is now deprecated for `Dropdown` and `URLPopover` ([source](https://make.wordpress.org/core/2023/03/03/editor-components-updates-in-wordpress-6-2/))
- [x] Switch to `switch_to_user_locale` instead of `switch_to_locale( get_user_locale() )` ([source](https://make.wordpress.org/core/2023/03/03/i18n-improvements-in-6-2/)) -- Not useful for us, we only do `switch_to_locale( get_user_locale() )` in one place, where we rely on `get_user_locale()` to get the current user by default. Switching to `switch_to_user_locale` would mean that we would have to fetch the user, which wouldn't be simpler.
- [x] Update `InspectorControls` now that `__experimentalGroup` is stabilized ([source](https://make.wordpress.org/core/2023/03/07/introduction-of-block-inspector-tabs/))  (in VideoPress) #29541
- [x] Remove usage of `Requests`. ([source](https://make.wordpress.org/core/2023/03/08/requests-library-upgraded-to-2-0-5-in-wordpress-6-2/))
    - [x] #29505
    - [x] #29542
    - [x] It's still used in some of our tests (see #27981). In this case, let's remove all those conditionals **once we make WordPress 6.2 the minimum required version**.

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-2](https://make.wordpress.org/core/tag/dev-notes+6-2)

As a bonus, there are new features we may be able to start using in some parts of the codebase, either now with a safeguard or once WordPress 6.2 is the minimum required version in Jetpack:

- [ ] `WP_HTML_Tag_Processor` ([source](https://make.wordpress.org/core/2023/03/07/introducing-the-html-api-in-wordpress-6-2/)) #32700

-------

For reference: prior art for WordPress 6.1 compat: #25417 
Internal: p9dueE-6vE-p2

**Comment by coder-karen** [comment]
Linking to this internal post as well with more info about dates and planning: p9dueE-6vE-p2

**Comment by jeherve** [comment]
> Changes to inline styles for InputControl and UnitControl ([source](https://make.wordpress.org/core/2023/03/03/editor-components-updates-in-wordpress-6-2/))

> any class names applied to the UnitControl component through its className prop will be applied to its outer wrapper element, instead of an inner input wrapper element.

@Automattic/jetpack-agora I see that VideoPress is using custom `className` on `NumberControl` and `RangeControl`. It may be worth taking a look and making sure nothing breaks layout with WordPress 6.2.

**Comment by dhasilva** [comment]
> I see that VideoPress is using custom `className` on `NumberControl` and `RangeControl`. It may be worth taking a look and making sure nothing breaks layout with WordPress 6.2.

I updated my local version to `6.2-RC2` and there seems to be no regressions with the components that use the custom `className` on `NumberControl` or `RangeControl` :+1:
