### ISSUE TITLE
Sharing buttons: Visual updates

### ISSUE THREAD

**Issue by davemart-in** [Automattic/jetpack#27817]
## Description

It was recently brought to Loop Team ’s attention that it’s high time we update the Sharing and Engagement button designs. The goal of this issue will be to outline this project and to track our progress.

## Progress tracker

After a little bit of digging, it looks like there are a variety of things to update:

### Sharing buttons

- [x] **[Jetpack primary PR](https://github.com/Automattic/jetpack/pull/28874)** - First, we'll need a JP PR to update the button styles and to make any necessary `/theme-tools/compat/` theme specific updates
- [x] **[Update Twentynineteen and Twentysixteen](https://github.com/Automattic/jetpack/pull/28876)** - Both themes have manual override styles for the `.sd-button` class
- [x] **[wp-calypso PR](https://github.com/Automattic/wp-calypso/pull/73126)** - Next, we'll need a PR to update the screen shown on https://wordpress.com//marketing/sharing-buttons/ which allows you to update your sharing button settings.
- [x] **[Jetpack "Official buttons"](https://github.com/Automattic/jetpack/pull/28961)** - Update sharing styles when "official buttons option is used
- [x] #29090

### Like / Reblog / Follow Comment / Reply / Todo buttons

- [x] **Update widgets.wp.com likes API styles** - Looks like the like / reblog buttons all come from wp.com D101354-code
- [x] **[Update O2 buttons](https://github.com/Automattic/p2/pull/6099)** - Reply / todo / follow conversation buttons shown in P2 need to be updated

### Legacy

- [x] **Older P2 theme** - The older P2 theme is no longer officially supported, but there are still sites running it on WP.com I suspect. John Godly recommended just making any changes directly to the theme on WP.com, which I plan on doing. D105156-code
- [ ] **Keyboard navigation** - The current like and P2 buttons are pretty bad when it comes to keyboard accessibility.
- [ ] **Remove old genericons code** - The P2 buttons all have genericons code scattered throughout. I plan to go back through and clean this up, but I want to do it in a separate PR.
- [ ] **Update a few social-logos** - Line widths still feel too light for "Press this", "Reddit", and "WhatsApp". We should probably update the icons that we use for each of those within: https://github.com/Automattic/social-logos

Note: #28861 is also being discussed as a possible extension of this project.

## Preview

Here is a preview of the updates we're proposing:

![image](https://user-images.githubusercontent.com/5634774/206280310-69c445ec-9a2f-4cb1-a81b-822f4f1ae13b.png)

Here's a breakdown of the new styles:

![image](https://user-images.githubusercontent.com/5634774/206280462-c681dabb-d70e-4496-b22f-19318c1a5d76.png)

Here's a preview with different color backgrounds:

![colors](https://user-images.githubusercontent.com/5634774/206282518-8e1dba92-b586-4396-9131-f50258e57eb6.png)

And a visual comparison of old vs. new:

![comparison](https://user-images.githubusercontent.com/5634774/206280955-ae96999b-75ff-4fbb-9659-d969dc6902f6.gif)

Big props to ollierozdarz for these designs.

**Comment by rfaile313** [comment]
@lessbloat -- suggestion to make the like button more clear if it's checked. Perhaps by inverting the colors. 

Right now, in my experience, have to really take a second and look to see if you "liked" something when it used to feel like an unconscious read. 

Example of suggestion:

current: 

<img width="333" alt="Screenshot 2023-03-15 at 11 09 23 AM" src="https://user-images.githubusercontent.com/13829168/225371481-c22aaf4c-e2c8-4a76-b317-bb6ac15041d2.png">

proposed (or similar):

<img width="563" alt="Screenshot 2023-03-15 at 11 09 15 AM" src="https://user-images.githubusercontent.com/13829168/225371556-9adca566-e5cb-4933-913d-4913570e66a0.png">

I know this seems trivial but in our use case we use the "like" button to signal to other members of the team that we're working on something since [reactions](https://github.com/Automattic/jetpack-social/tree/trunk/app/modules/reactions) never really got shipped.

**Comment by davemart-in** [comment]
Thanks for the feedback @rfaile313! You're not the only one to share this feedback. There have been a couple of other folks asking for a change here: p7DVsv-gLZ-p2#comment-44924

I'd still like to keep the new design in place for at least one more week, then ask around to see how people are finding it.

**Comment by rfaile313** [comment]
Sounds good @lessbloat thanks for the consideration

**Comment by rfaile313** [comment]
Hey @lessbloat I am still on team more noticeable liked button :) just wanted to share

**Comment by davemart-in** [comment]
Thanks for sharing @rfaile313! @ollierozdarz and I are going to be revisiting all of the feedback we've received this coming Monday.

**Comment by annezazu** [comment]
Found this issue and wanted to +1 on making the liking action more visible.

**Comment by correliebre** [comment]
Adding another +1! I still have trouble with knowing whether I liked or didn't like something.

**Comment by jgcaruso** [comment]
@davemart-in  Hi there, I stumbled on this while doing some searching to see if the Like button iframe was at all customizable. Looking at the code in D101354-code it doesn't seem like it is but have there been any discussions about making that possible if it isn't?

For example, passing query params to define styles like:
1. Make the the gravatar a circle instead of a square
2. change the color used for the the "liked" state

**Comment by davemart-in** [comment]
@jgcaruso it's not on our teams immediate radar, though I know the idea has come up a number of times. I do agree that it would be cool to be able to introduce some customization options.
