### ISSUE TITLE
Jetpack fonts: improvements

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#28118]
### Impacted plugin

Jetpack

### What

Performance and other improvements to Jetpack Google Font module.

### TODO

- [ ] [Avoid too big API requests and cache objects](https://github.com/Automattic/jetpack/issues/28119)
- [x] [WP Fonts API deprecation changes in GB 14.9](https://github.com/Automattic/jetpack/issues/28063) once the API stabilizes in Gutenberg. [PR](https://github.com/Automattic/jetpack/pull/28054)
- [ ] After above performance issue is sorted, ensure all previously added ([one](https://github.com/Automattic/jetpack/pull/27441), [two](https://github.com/Automattic/jetpack/pull/27854)) new fonts are re-added if they were reverted:
    - https://github.com/Automattic/jetpack/pull/28122
    - https://github.com/Automattic/jetpack/pull/28123
- [ ] [Use dynamic browser agent](https://github.com/Automattic/jetpack/issues/28120); we now request API always as "Firefox" while Google API actually returns different response depending on browser.

**Comment by simison** [comment]
These APIs are deprecated longer ago already.
