### ISSUE TITLE
Contact Form: When using "Checkbox with multiple items" - commas break checklist

### ISSUE THREAD

**Issue by csonnek** [Automattic/jetpack#2917]
When setting up a "checkbox with multiple items" field, if there is a comma in one of the fields, it breaks that entry into two lines due to the commas in the shortcode defining each field item. 

Example:
`[contact-field label='Multiple Checkboxes' type='checkbox-multiple' options='I love multiple checkboxes!,I like multiple checkboxes.,Multiple checkboxes are OK,I guess.,I wish I could have had them years ago!,Checkboxes are so last year.,I love Jetpack!'/]`

Intended display:
- [ ] I love multiple checkboxes!
- [ ] I like multiple checkboxes.
- [ ] Multiple checkboxes are OK, I guess.
- [ ] I wish I could have had them years ago!
- [ ] Checkboxes are so last year.
- [ ] I love Jetpack!

Actual display:
- [ ] I love multiple checkboxes!
- [ ] I like multiple checkboxes.
- [ ] Multiple checkboxes are OK
- [ ] I guess.
- [ ] I wish I could have had them years ago!
- [ ] Checkboxes are so last year.
- [ ] I love Jetpack!

Confirmed that commas have no effect in a single checkbox field entry.

**Comment by spencerberry** [comment]
This is still an issue.

In the editor everything looks fine:
![Screen Shot 2019-11-23 at 13 05 35](https://user-images.githubusercontent.com/1162736/69485275-fd873f00-0df1-11ea-9c94-46949d639b27.png)

In the live site, however, each comma creates a new line and checkbox:
![Screen Shot 2019-11-23 at 13 05 12](https://user-images.githubusercontent.com/1162736/69485276-0710a700-0df2-11ea-8351-731ba32a2675.png)

16865861-hc

**Comment by formosattic** [comment]
+1 2523649-hc

**Comment by chickenn00dle** [comment]
Another case here: 2525028-zen

**Comment by goblinartificer** [comment]
Also in 18883111-hc

**Comment by macmanx2** [comment]
Just noting that this is still an issue, even under the Block Editor now.

Here's how it looks in the editor:

![Screen Shot on 2020-06-25 at 15-39-36](https://user-images.githubusercontent.com/4856235/85802867-b13f0d00-b6fa-11ea-8066-25c52bf063d7.png)

Here's how it looks in the published post:

![Screen Shot on 2020-06-25 at 15-40-08](https://user-images.githubusercontent.com/4856235/85802894-bbf9a200-b6fa-11ea-9bed-a74338690eed.png)

Reported via https://wordpress.com/forums/topic/block-editor-contact-form-possible-bugs/

**Comment by jordesign** [comment]
Another instance of this in 4000384-zd-woothemes - with someone wanting to add long descriptions (passages of text) into the labels.

It looks like this is something unlikely to be fixed - is this correct?

**Comment by jeherve** [comment]
> It looks like this is something unlikely to be fixed - is this correct?

This is not something we're working on at the moment, but we may get to it some time in the future. If we do, we'll update this issue.
