### ISSUE TITLE
VideoPress: play/pause video in the front-end

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#29758]
When the hover effect is enabled, the video should also be handled in the front end. The implementation is quite different from the block editor context considering the libraries available are not the same.

### Tasks list

- [ ] https://github.com/Automattic/jetpack/issues/29870
- [ ] Detect the block instances that have the previewOnHover enabled
- [ ] Play/Stop when mouse entering/mouse leaving

**Comment by retrofox** [comment]
.
