### ISSUE TITLE
My Jetpack: Introduce standalone options in product card menu

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#29901]
Depends on #29904 #29903 #29902 

You can add in the product menu the default option to install or activate the standalone plugin (if available).

![Image](https://user-images.githubusercontent.com/1663717/229812665-92da35e0-0405-4fb1-a1bd-c6e8ab650680.png)

It will require the adjustment to force API to install and activate the standalone plugin and not Jetpack.

Some steps to acomplish this:

- [x] add side-effect action to trigger the installation, the same way we have one for activating the product - PR: #30143 
- [x] add button to "Install X plugin" if the product has a standalone plugin and it's not installed or active - PR: #30153
- [x] handle the click of the button to dispatch the side-effect action - PR: #30168

**Comment by lhkowalski** [comment]
I will take a look into the first step, the side-effect action.

**Comment by lhkowalski** [comment]
Going to look into adding the menu option for installing the plugin as well. We have some code history to help this taks on [this old closed PR](https://github.com/Automattic/jetpack/pull/29840/files#diff-0f409ceb5046d993dec9c29a4ed60662af5899bc168d13994b84b97a8244f803R77).

**Comment by lhkowalski** [comment]
Now I am going to connect the action menu with the action, and also fix the small menu issues that @renatoagds commented about on the last PR.

**Comment by lhkowalski** [comment]
We merged the changes that we needed to make this happens. There are some UI/UX polishing being made as follow-ups to this issue, but they all have their own issue here on GH.
