### ISSUE TITLE
Maintenance: remove old contact form module from the Jetpack plugin

### ISSUE THREAD

**Issue by ice9js** [Automattic/jetpack#30551]
Since we've now enabled the new forms package in #28791, the old contact form module code inside the Jetpack plugin is now obsolete and can be removed. Once we're ready, I believe these would be the steps to do it:

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/35338
- [x] Remove [legacy initiation code from contact-form.php](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/contact-form.php). I think the entire file could be simplified to just [this line](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/modules/contact-form.php#L34).
- [x] Remove [the contact form module directory](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/modules/contact-form).
- [ ] [Google Drive helper class](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/lib/class-jetpack-google-drive-helper.php) can also be removed, but worth double checking. The logic is [duplicated inside the package](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/forms/src/service/class-google-drive.php) but maybe warrants its own library if we need similar functionality in other places.
- [ ] Remove old [contact form editor blocks' extension directory](https://github.com/Automattic/jetpack/tree/trunk/projects/plugins/jetpack/extensions/blocks/contact-form).
- [ ] Clean up [the config for Jetpack's JavaScript bundle](https://github.com/Automattic/jetpack/blob/ede04cf44e08fc8856d0fcb767de8bae2f285254/projects/plugins/jetpack/class.jetpack-gutenberg.php#LL748C6-L748C29).
```

**Comment by jeherve** [comment]
This will be tackled in #35652.

**Comment by monsieur-z** [comment]
Closing, since the project to deprecate the module is done.
pf5801-Aj-p2
