### ISSUE TITLE
AI Assistant streaming endpoint tracking

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#30738]
Make sure in the new streaming endpoint, we’re tracking properly what we were tracking before, in the previous endpoint

**Comment by lhkowalski** [comment]
I went through the backend code, following the line of execution for a given chat completion request, and taking note of any log or tracking record that we may do on the request.

A summary of the flow and the log events:

**For the old version:**

1. File `class-wpcom-rest-api-v2-endpoint-ai.php` - API entrypoint
   - No logs or event tracking
1. File `class-jetpack-ai-helper.php`
   - `mark_post_as_ai_assisted` - add metadata to a post counting the number of times some AI request got processed coming from the post
1. File `lib/openai/openai.php` - method `request_gpt_completion`
   - possible `gpt3_completion_error`
   - possible `gpt3_bad_word` and related moderation logs, if the prompt contains bad words
   - estimated costs for `openai_gpt3`
   - possbile `gpt3_completion`

**For the new, Streamed Version:**

1. File `endpoints/jetpack-openai-query.php` - API entrypoint
   - No logs or event tracking
1. File `class-jetpack-ai-helper.php`
   - It's not used anymore, so the `mark_post_as_ai_assisted` call is missing
   - something to add on the new code
1. File `lib/openai/openai.php` - method `request_chat_completion`
   - The method changed, but both methods track the same logs and events:
   - possible `gpt3_completion_error`
   - possible `gpt3_bad_word` and related moderation logs, if the prompt contains bad words
   - estimated costs for `openai_gpt3`
   - possible `gpt3_completion`

So, by comparing the flows on the backend, the only thing that is different is the tracking of the number of AI assisted calls being performed on a given post. I don't think it's being used internally for any kind of control, but we can add it so we can fetch insights about it in the future.

Tomorrow I will check the frontend code as well.

**Comment by lhkowalski** [comment]
On the frontend code, there was no tracking before the change to streaming. The code for streaming the response included a tracks event for `jetpack_ai_gpt3_completion` so we started to track it after the change. No action needed on this side.

**Comment by lhkowalski** [comment]
Edit: I was seeing it as low priority but seems like the post_id goes all the way down to the logstash defaults array, so it gets registered on all the important logs that we do. This is done for WPCOM sites.

Here are the action items to comply with this:

- [ ] include code to mark a given post as AI assisted, if possible
- [x] send the post_id being edited on the completion request, so it can be logged on the backend - PR: #30765
- [x] expect the post_id on the backend and inject it into the OpenAI instance, so it makes it's way to logstash - Diff: D111178-code

**Comment by lhkowalski** [comment]
I will skip the code to mark the post as AI assisted for now, so I can check the issue causing #30780.

**Comment by lhkowalski** [comment]
We identified that the `user_id` is not present on the events from the backend due to not being available for some kinds of requests. More details here: p1684786000152359-slack-C054LN8RNVA

We planned a solution that may require a small change on the JWT token generation to include the `user_id` on the payload, as well as changes on the backend to expect this data, log it, and send it when the request is being performed by a Jetpack site.

**Comment by dereksmart** [comment]
Note that user_id is also not being recorded in wpcom simple either.

**Comment by robfelty** [comment]
I think we could use `tracks_get_userid`, which is used for example for `wpcom_post_publish` events.

**Comment by lhkowalski** [comment]
I am getting back to this to work on the `user_id` tracking, since it may be relevant for analytics purposes.

**Comment by lhkowalski** [comment]
Just to post an update, these are the steps to solve the user_id issue:

- [x] include the user_id field when issuing the JWT token (D113109-code, merged)
- [x] make sure JWT creation requests from Jetpack sites have the requester user_id included (#31262)
- [x] expect the user_id field on the completion endpoints and use it to set the current user_id (D113174-code, merged)

**Comment by lhkowalski** [comment]
Now we have the user_id tracking in place. It will be fixed for WPCOM sites tomorrow (given the daily deployment there) and will be completely fixed on Jetpack sites as soon as we ship a new version.

**Comment by lhkowalski** [comment]
The last task here was related to marking posts as AI assisted. Turns out we have another issue referencing this change, so I will close this as dones since all the other stuff is done.

The remaining work will be tracked on #31235.
