### ISSUE TITLE
My Jetpack: show number of available free requests in AI card

### ISSUE THREAD

**Issue by nunyvega** [Automattic/jetpack#31036]
Whenever a user is on a free plan, show the number of free requests available

**Comment by ederrengifo** [comment]
I got two ideas / options based on our appetite:

**Option 1: Full use of our new cards layout**
- Use the new stats area to communicate the requests with colors
- A helper to explain more about the limited requests
- A more explicit "Get unlimited" CTA
<img width="1789" alt="jetpack-cards-improvement-1" src="https://github.com/Automattic/jetpack/assets/10525007/f4a8611e-7128-499e-be1a-044c90f66a6f">

**Option 2: A simpler communication**
- Use the existing text to communicate the remaining requests
<img width="1795" alt="jetpack-cards-improvement-2" src="https://github.com/Automattic/jetpack/assets/10525007/3f6f8fec-29fb-4aee-a098-b92a25cb3cbd">

The first option provides more information and could encourage better conversion, but it might be more expensive. Option 2 is simpler and might be enough for the MVP release. Thoughts? cc @keoshi @nunyvega

**Comment by keoshi** [comment]
@ederrengifo I like them both, but actually prefer option 2 for clarity purposes at least in the trial phase.

I believe the metrics in the new My Jetpack cards are all cumulative (sum of everything used or taken advantage of so far), right? This introduces a new subtractive model, where they start with 20 and see that number go down as they use the product.

We could clarify this by adding the language you have on the second one:

> **20** requests remaining/left

**Comment by ederrengifo** [comment]
I'm testing here an option with "left" instead of "remaining." It might add more clarity. Also, I removed the red "0"; if the idea is to make it simple for the release, we can show it in the same black color. If we are all ok with this, let's use this option then:

![Image](https://github.com/Automattic/jetpack/assets/10525007/1cde0dbd-3e4c-4459-8d1e-b0f09638d4dc)

**Comment by retrofox** [comment]
### Tasks list

- [ ] Expose AI Assistant feature data in the global state https://github.com/Automattic/jetpack/pull/31238
- [ ] Requests data once the product activates https://github.com/Automattic/jetpack/pull/31252
- [ ] Update the card IU according to the feature data https://github.com/Automattic/jetpack/pull/31252
- [ ] Polish the AI Assistant product card states

**Comment by retrofox** [comment]
we may hold on for now p1686164926817549/1686147682.537239-slack-C054LN8RNVA

**Comment by lhkowalski** [comment]
We now have a stable counting system for the requests, so I will move this from hold to backlog.

**Comment by jeherve** [comment]
I'll reopen this if that's okay with you, since it's still an ongoing issue.
