### ISSUE TITLE
AI Assistant: block client requests when the site achieves the requests limit

### ISSUE THREAD

**Issue by retrofox** [Automattic/jetpack#31198]
Once the site achieves the requests limit and requires an upgrade, we should block the client from hitting the endpoint for at least one minute. We should show let the users know by displaying a message.

**Comment by retrofox** [comment]
### Tasks list

-  [ ] https://github.com/Automattic/jetpack/issues/31225
-  [ ] https://github.com/Automattic/jetpack/pull/31229
-  [ ] Block async ai requests when required
