### ISSUE TITLE
Paid Stats: Add Stats card on My Jetpack landing page

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#31343]
![Image](https://github.com/Automattic/jetpack/assets/1425433/380505a1-961f-4766-83e4-d773b257810b)

![Image](https://user-images.githubusercontent.com/1425433/245349967-2ff4b456-520a-4a33-9181-4a3e8813e7de.png)

(from [this comment](https://github.com/Automattic/jetpack/issues/31343#issuecomment-1589987410).)

Note: "Learn more" should become a "Manage" button linking to the Stats dashboard if a stats plan has already been purchased.

```[tasklist]
### Tasks
- [x] Create a My Jetpack card for Jetpack Stats with support for just the "Learn More" button behind a feature flag. (https://github.com/Automattic/jetpack/pull/31531)
- [x] Add support for an "Activate" button, automatically installing and enabling the Jetpack plugin and completing the connection. (https://github.com/Automattic/jetpack/pull/31589)
- [x] Remove the feature flag and release the My Jetpack card for the July release. (https://github.com/Automattic/jetpack/pull/31589)
- [x] Replace the "Activate" button with an "Upgrade" button behind a feature flag. (https://github.com/Automattic/jetpack/pull/31629)
- [ ] https://github.com/Automattic/jetpack/issues/32309
- [x] Remove the feature flag and release for the August release. (https://github.com/Automattic/jetpack/pull/32020)
```

**Comment by jsnmoon** [comment]
We may be able to ship this early and incrementally if we build it like so:

1. Build out a My Jetpack card for Jetpack Stats with support for just the “Learn More” button behind a feature flag.
2. Add support for an “Activate” button, which will automatically install and enable the Jetpack plugin and complete the connection.
3. Remove the feature flag and release the My Jetpack card for the July release.
4. Replace the “Activate” button with an “Upgrade” button behind a feature flag.
5. Once ready, remove the feature flag and release for the August release.

**Comment by jeherve** [comment]
I wanted to note that this currently has one issue. Maybe you're already aware of that, but I wanted to point it out:

1. Install the Jetpack Beta plugin
2. Via the Jetpack Beta plugin, install the Bleeding Edge version of the **Boost** plugin (this will get you the latest version of My Jetpack on a site where the Jetpack plugin is not installed)
3. Go to Jetpack > My Jetpack
4. You will see the Stats card, with a link to "install stats"
5. When clicking on it, you're redirected to a purchases page in Calypso, then immediately redirected to https://wordpress.com/stats/day
6. No Jetpack plugin is installed on the site.

**Comment by kangzj** [comment]
Thanks for surfacing this @jeherve 👍 . I'm working on a fix now.

**Comment by kangzj** [comment]
Hi @jeherve  we shipped [a temporary fix](https://github.com/Automattic/jetpack/pull/31689) to hide the card for standalone plugins before we can make it work when Jetpack plugin doesn't exist.

I imagine we should allow the installation of Jetpack (there are APIs and existing example) and then redirect to purchase in the case?

cc @jsnmoon

**Comment by jsnmoon** [comment]
Thanks for the quick fix, @kangzj. Your proposal sounds solid and is the same idea I had in mind as well 👍

**Comment by kangzj** [comment]
I tracked the unfinished task with https://github.com/Automattic/jetpack/issues/32309, and I'm closing this one for now.
