### ISSUE TITLE
WordPress 6.3 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#31638]
WordPress 6.3 is set to release on August 8, 2023.

- Planning: [make.wordpress.org/core/6-3](https://make.wordpress.org/core/6-3/)

Let's use this issue to keep track of anything that may come up until then.

- [x] Update our "tested up to" version to 6.3 #31910
- [x] Update the version of WordPress required for Jetpack from WP 6.1 to WP 6.2:  ~**On hold for now, waiting for 12.6**~ #32762 
- [x] Remove 6.1 backward-compatible checks ~**On hold for now, waiting for 12.6**~ #32772

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-3](https://make.wordpress.org/core/tag/dev-notes+6-3)

- [x] [Layout updates](https://make.wordpress.org/core/2023/07/14/layout-updates-in-the-editor-for-wordpress-6-3/): changes in CSS specificity
- [x] [WP_Query used internally in get_pages()](https://make.wordpress.org/core/2023/07/14/wp_query-used-internally-in-get_pages/)
- [ ] [Improved Caching for Database Queries in WP_User_Query](https://make.wordpress.org/core/2023/07/14/improved-caching-for-database-queries-in-wp_user_query/)
- [x] [Image performance enhancements in WordPress 6.3](https://make.wordpress.org/core/2023/07/13/image-performance-enhancements-in-wordpress-6-3/): ensure that those enhancements do not conflict with our Lazy Images implementation.

Below, let's keep track of things we can start implementing once WordPress 6.3 is the minimum required version, in #32865.

- #32852
- #32853
- #32854
- #32863
- #32864

-------

For reference: prior art for WordPress 6.2 compat: #27795

**Comment by jeherve** [comment]
> [Improved Caching for Database Queries in WP_User_Query](https://make.wordpress.org/core/2023/07/14/improved-caching-for-database-queries-in-wp_user_query/)

@Automattic/jetpack-kernel Do you think this is something that may impact us in sync?

**Comment by sergeymitr** [comment]
Thanks for the ping @jeherve, there might be an issue here.

@bisko, it looks like we're querying user ID's directly from the database, and then use `WP_User_Query` to fetch users by those ID's [here](https://github.com/Automattic/jetpack/blob/12ab265df2115293f5762b5675e64ecc43eef214/projects/packages/sync/src/replicastore/class-table-checksum-usermeta.php#L48-L69).
Do you think there might be a problem with users being in the database, but `WP_User_Query` operating with an older cache and not finding those users?
Technically it shouldn't happen as the cache gets invalidated every time there's a change to the database, but it will occasionally happen, so may be we only should make sure it fails gracefully if that happens.
