### ISSUE TITLE
Newsletter modal: improvements & release

### ISSUE THREAD

**Issue by simison** [Automattic/jetpack#31862]
Now that we have most of the work in (https://github.com/Automattic/jetpack/pull/31393), next up some polish and release tasks:

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/31867
- [ ] #31865
- [ ] https://github.com/Automattic/jetpack/issues/31866
- [ ] https://github.com/Automattic/jetpack/pull/32230
- [x] Ensure links to “edit” template work from WP.com and Jetpack.
- [x] Tweak who sees the modal. This is mostly done. But, we want to hide modal if paywall block is on the page. And we may want to improve how we detect if a user is already subscribed for self-hosted jetpack sites. Method we're using now is wpcom centric: p1690473523421839-slack-C052XEUUBL4
- [x] Revisit the "modal" copy to change to "pop up" which seems more common and better known term among customers. (slack ref p1689250657718169-slack-C052XEUUBL4)
- [x] Release: Roll out for .com sites all themes
- [x] Release: Roll out for Jetpack sites
- [ ] Enhancement: Update success message to be a green-styled alert vs plain text.
- [ ] Enhancement: Show confirmation message in subscribe modal before closing and reloading page.
```
