### ISSUE TITLE
AI Assistant: Proofread posts MVP 🎨

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#31946]
Provide an MVP for proofread the post.

More context is provided here: p1HpG7-nIQ-p2
```[tasklist]
### Tasks
- [x] AI Assistant: Insert AI Assistant sidebar #31954
- [x] AI Assistant: Insert Proofread component in sidebar panel #31963
- [x] AI Assistant: Insert modal for proofread feedback #31963
- [ ] AI Assistant: Add proofread logic and prompts
- [ ] AI Assistant: Connect panel and proofread logic
- [ ] AI Assistant: Release new proofread feature
```

**Comment by ederrengifo** [comment]
Here are more details about the design cc @renatoagds 

- From the sidebar after the user clicks on "Publish" ([Prototype](https://www.figma.com/proto/gG1smMHbNGas0qwP9y6RwK/Jetpack-AI-Assistant?type=design&node-id=3609-17611&viewport=680%2C-4581%2C0.13&t=VOkD7a6xgTiXHx4w-0&scaling=min-zoom&starting-point-node-id=5304%3A25201&show-proto-sidebar=1))
- From the Jetpack sidebar when open the AI subsection ([Prototype](https://www.figma.com/proto/gG1smMHbNGas0qwP9y6RwK/Jetpack-AI-Assistant?type=design&node-id=3609-17611&viewport=940%2C-4360%2C0.13&t=VOkD7a6xgTiXHx4w-0&scaling=min-zoom&starting-point-node-id=5306%3A25463&show-proto-sidebar=1))
- When triggered the first time, feedback is generated, but then users have a "refresh" action to generate new feedback

![Image](https://github.com/Automattic/jetpack/assets/10525007/e1b59890-c86f-4d98-b0f5-0368ba3c02fc)

**Comment by renatoagds** [comment]
We ended up reverting the initial pushes because of a problem in P2. Returned with the changes in #32001 , with more context about the problem
