### ISSUE TITLE
Newsletters: Paywall block TODO

### ISSUE THREAD

**Issue by lezama** [Automattic/jetpack#32124]
peKye1-fd-p2

```[tasklist]
### Tasks
- [x] Check the Block Preview in the editor
- [ ] https://github.com/Automattic/jetpack/pull/32182
- [ ] https://github.com/Automattic/jetpack/pull/32190
- [ ] https://github.com/Automattic/jetpack/pull/32201
- [ ] https://github.com/Automattic/wp-calypso/issues/79976
- [ ] https://github.com/Automattic/jetpack/issues/32334
- [x] Add block transform – p2-p9MPsk-3Zr#comment-27764
- [ ] We should ensure excerpts, social shares etc continue functioning without leaking paywalled content. – jetpack_filter_excerpt_for_newsletter 👀
- [x] Test Emails
- [x] Test Reader – RSS — app
- [x] We need to consider how this will work in post editor within the native apps, or “fail gracefully” meanwhile. See Project pcdRpT-3rt-p2
- [x] Release
```

**Comment by simison** [comment]
> Test Emails
> Test Reader – RSS


Will need some styling added, [issue for the reader](https://github.com/Automattic/wp-calypso/issues/79976).

There should be fieldguide docs and example PRs for both reader and emails.
