### ISSUE TITLE
🎨 AI Extension: Designers feedback (UX/UI)

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#32292]
This issue is the tracking issue for all issues and discussions branched from review made by Designers.

More context and details about the review and discussions: p1691144250247699-slack-C054LN8RNVA

All defined points will generate an specific issue.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/32293
- [ ] https://github.com/Automattic/jetpack/issues/32294
- [ ] https://github.com/Automattic/jetpack/issues/32296
- [ ] https://github.com/Automattic/jetpack/issues/32298
- [ ] https://github.com/Automattic/jetpack/issues/32299
- [ ] https://github.com/Automattic/jetpack/issues/32295
- [ ] https://github.com/Automattic/jetpack/issues/32297
- [ ] https://github.com/Automattic/jetpack/issues/32313
```

**Comment by ederrengifo** [comment]
I ran a test and there is a couple of things I'm noticing in the testing that might be or not related to all the issues:

- [x] **The toolbar is not sticky anymore for mobile and I think that's a Gutenberg behavior. I also noticed our implementation shows a horizontal scrollbar in the toolbar:**

Toolbar always present in a regular JN site:
![Screen Shot 2023-08-10 at 14 10 10](https://github.com/Automattic/jetpack/assets/10525007/64c6417d-b9db-4153-a512-407561df5acf)

But it doesn't work like that in our testing site:
![Screen Shot 2023-08-10 at 14 11 12](https://github.com/Automattic/jetpack/assets/10525007/e91f6a49-1786-4a65-8c7a-2a05460fd6fb)

Toolbar with a horizontal scrollbar:
![Screen Shot 2023-08-10 at 14 12 23](https://github.com/Automattic/jetpack/assets/10525007/fff2a94a-bcd8-4888-94b0-e0dc07f31282)

- [ ] **It would be great if when the AI input is called from the toolbar, we can auto-scroll to the bottom of the form. Is that possible before the release?**

**Comment by dhasilva** [comment]
Let's close this issue, the remaining two tasks are separate.
