### ISSUE TITLE
Blocks: ensure visibility of Jetpack blocks in w.org profile

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#32408]
### Impacted plugin

Jetpack

### What

As a site owner, I would like to be able to see all of the blocks brought to my site via Jetpack on the WordPress.org page.

### How

This needs to be done via adding block.json files to Jetpack to match the blocks that we are including in our bespoke bundling process. While splitting this up to use the block.json file is blocked a bit by the performance hit and the current Gutenberg work for async loading, we can add the block.json files now and begin to gain value.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/32187
- [ ] https://github.com/Automattic/jetpack/pull/32431
- [ ] https://github.com/Automattic/jetpack/pull/32432
- [ ] https://github.com/Automattic/jetpack/pull/32433
- [ ] https://github.com/Automattic/jetpack/pull/32497
- [ ] https://github.com/Automattic/jetpack/pull/32508
- [ ] https://github.com/Automattic/jetpack/pull/32536
```

*****

Primary issue: #17099
Internal reference: pedMtX-RS-p2

**Comment by sdixon194** [comment]
Is this task wrapped up now?

**Comment by kraftbj** [comment]
We still need to update the block.json with SVG descriptions of the icons after discovering that's an undocumented option. @monsieur-z is working on that.
