### ISSUE TITLE
Blocks: use a single source of truth for blocks metadata

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#32602]
Following https://github.com/Automattic/jetpack/issues/32408, a `block.json` metadata file was created for each block so that wp.org could list them on [the Jetpack plugin page](https://wordpress.org/plugins/jetpack/). However, the block registration methods in both the back and front ends don't consider these files yet: they read metadata from an object that's exported in a JS file. Metadata is duplicated.

The recommended method for block registration is to specify a path to a `block.json` file. We should try that and get rid of data that's not present in that file.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/32697
- [x] Switch all Beta blocks to be registered via their block.json file
- [ ] https://github.com/Automattic/jetpack/pull/32698
- [ ] https://github.com/Automattic/jetpack/pull/32815
- [ ] https://github.com/Automattic/jetpack/pull/33073
- [ ] https://github.com/Automattic/jetpack/pull/33076
- [ ] https://github.com/Automattic/jetpack/issues/33174
- [ ] https://github.com/Automattic/jetpack/issues/32603
- [ ] https://github.com/Automattic/jetpack/issues/32604
- [ ] https://github.com/Automattic/jetpack/issues/33173
- [x] Switch all Experimental blocks to be registered via their block.json file
```
