### ISSUE TITLE
WordPress 6.4 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#32865]
WordPress 6.4 is set to release on November 7, 2023.

- Planning: [make.wordpress.org/core/6-4](https://make.wordpress.org/core/6-4/)
- PT: pf5801-82-p2 

Let's use this issue to keep track of anything that may come up until then.

```[tasklist]
- [ ] #33525
- [ ] https://github.com/Automattic/jetpack/issues/33643
- [ ] https://github.com/Automattic/jetpack/issues/33642
- [ ] https://github.com/Automattic/jetpack/issues/33654
- [ ] https://github.com/Automattic/jetpack/issues/33655
- [ ] https://github.com/Automattic/jetpack/pull/33709
- [ ] https://github.com/Automattic/jetpack/issues/33779
- [ ] https://github.com/Automattic/jetpack/issues/33874
```

And **in a follow-up plugin release** (most likely the December release, 12.9), to give folks time to update:

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/pull/34127
- [ ] https://github.com/Automattic/jetpack/issues/34209
- [ ] #32852
- [ ] #32853
- [ ] #32854
- [ ] #32863
- [ ] #32864
- [ ] #31714
- [ ] #31716
- [x] Coordinate deactivation of the Lazy Images feature in Jetpack in favor of Core's (see #33048)
```

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-4](https://make.wordpress.org/core/tag/dev-notes+6-4)

-------

For reference: prior art for WordPress 6.3 compat: #31638

**Comment by jeherve** [comment]
Marking this one as done; all tasks have now been handled.
