### ISSUE TITLE
Feature request: add a new Top Posts & Pages Block

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/jetpack#32937]
### What

I would love to see a new block to automatically display a certain number of "top posts" by views or likes, perhaps over a certain time period (or possibly additional sorting options for the Query Loop to accomplish the same thing).

Initial request in 6784524-zd-a8c:
> Do you have anything for most popular posts or trending posts? I didn't see that option in the query loop.

### Why

This was previously possible with the legacy Jetpack "Top Posts & Page" widget. See pdf5j4-4C-p2 regarding the decision to leave that widget "as is." For any site using a Site Editing theme, that widget is inaccessible, and similar functionality would otherwise require a plugin.

### How

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/34153
- [x] Deprecate (i.e. hide) [the existing widget](https://github.com/Automattic/jetpack/blob/848a071ff7904dd0ed680c5df21cb1ffef580f06/projects/plugins/jetpack/modules/widgets/top-posts.php) in favor of the block, with `widget_types_to_hide_from_legacy_widget_block`
- [ ] https://github.com/Automattic/jetpack/issues/34484
- [ ] https://github.com/Automattic/jetpack/pull/34479
- [ ] https://github.com/Automattic/jetpack/issues/34505
- [ ] https://github.com/Automattic/jetpack/issues/34506
- [ ] https://github.com/Automattic/jetpack/pull/34558
- [ ] https://github.com/Automattic/jetpack/pull/34717
- [ ] https://github.com/Automattic/jetpack/pull/34614
- [x] Release the block - move from beta to production
```

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept
- CC: @jeherve perhaps this is something a Jetpack Block could do!

**Comment by jeherve** [comment]
> perhaps this is something a Jetpack Block could do!

Yeah, definitely! I'm surprised this issue doesn't exist yet!

We already have a [Top Posts & Pages widget](https://jetpack.com/support/extra-sidebar-widgets/top-posts-pages-widget/), we should turn it into a block.

**Comment by jamiepalatnik** [comment]
Just wanted to add a +1 to this based on my own user interactions. This also sometimes comes up because users are confused by the Tenaz theme demo content, which has a Trending section but no way to automatically feature trending posts: https://wordpress.com/theme/tenaz

**Comment by devNigel** [comment]
+1 

It would be nice if the popular posts could be configured to show popular posts in different ranges like last 24 hours, last 7 days, last 30 days, etc.

**Comment by jeherve** [comment]
I'll reopen this issue so we can use it to keep track of the different tasks that need to be completed before the block can be shipped to production. I'll update the task list above accordingly.

**Comment by Aurorum** [comment]
PR in #34558 to tidy up thumbnails. 

| Before | After |
|--------|--------|
| <img width="574" alt="Screenshot 2023-12-10 at 19 32 06" src="https://github.com/Automattic/jetpack/assets/43215253/4a9c8440-8f58-4f1a-aeae-8365a4eeed74"> | <img width="696" alt="Screenshot 2023-12-10 at 19 32 15" src="https://github.com/Automattic/jetpack/assets/43215253/b25ad468-db45-4057-8b37-97958ab264f1"> |

**Comment by kangzj** [comment]
Thanks for all your hard work @Aurorum @jeherve! Now we only need to move it from `beta` to `production` when ready!

**Comment by jp-imagines** [comment]
Just noting that we got another request for this in 7800942-zd-a8c, as it seems the legacy widget is no longer available (at least on this newer Simple site using a non-block theme).

Any ideas when this might be moved to production? 🙏

**Comment by brittanygray902** [comment]
Adding that a user in this 8554703-zen interaction was inquiring about the widget as well. I've mentioned the shortcode work around for now.
