### ISSUE TITLE
Lazy Images: deprecate functionality

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#33048]
### Impacted plugin

Jetpack, Boost

### Quick summary

The Lazy Images functionality of Jetpack and Boost is not compatible with new work being done in Gutenberg (shipped 16.6). This feature has overall been seeing reduced necessity due to the advancement of browser's native loading.

This is to track the overall deprecation of this feature.

### Logs or notes

Internal reference: pdWQjU-wV-p2

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/33039
- [ ] https://github.com/Automattic/jetpack/issues/33049
- [ ] https://github.com/Automattic/jetpack/issues/33170
- [x] Deprecate package
```

**Comment by kraftbj** [comment]
Open question that I have:

Do we want to kill off the feature straightaway or have it stop working with WP 6.4, so existing clients can continue to use it for the moment until they update? I don't have a strong opinion and curious what others think.

**Comment by jeherve** [comment]
@kraftbj I would have it stop working with Jetpack 12.7, that will come out around the time of WP 6.4.

I did have a question on my end as well, about the deprecation of the package:

Should we mark all the methods in the package as deprecated then deprecate the whole package, or should we leave it as it is and only stop using the package in our plugins? If the package remained usable, without any deprecation warnings, we could create a small plugin that only requires the package, for folks who would want to continue to use this package over Core's functionality.

cc @haqadn

**Comment by kraftbj** [comment]
> @kraftbj I would have it stop working with Jetpack 12.7, that will come out around the time of WP 6.4.

Do you think we should aim for the October release to have the disable/unable to activate changes? But for sites actively using it without manual intervention, let it ride until removing it outright in November?

> Should we mark all the methods in the package as deprecated then deprecate the whole package

Personally, I would deprecate the package since we actively know it will break functionality in upcoming versions of WordPress without an intent on our end to resolve. Folks can still use a deprecated package/functions, but at least they should check to see why we did and if it matters to them. I wouldn't, say, delete them from Packagist or anything like that.

**Comment by jeherve** [comment]
> Do you think we should aim for the October release to have the disable/unable to activate changes? But for sites actively using it without manual intervention, let it ride until removing it outright in November?

Yes, that's what I was planning. 👍

> Personally, I would deprecate the package since we actively know it will break functionality in upcoming versions of WordPress without an intent on our end to resolve.

👍

**Comment by foleynotrose** [comment]
Oops didn't mean to close this! But maybe it's ready to be closed?

**Comment by jeherve** [comment]
No, it's not quite complete for Boost just yet, so it needs to remain opened for now. 👍

**Comment by foleynotrose** [comment]
@pehaa would you mind just keeping an eye on this issue, since you did a lot of the work in updating the docs? It was Daniel's before.
