### ISSUE TITLE
Lazy Images: deprecate from the Jetpack plugin

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#33049]
### Impacted plugin

Jetpack

### Quick summary

Jetpack-specific work for #33048 

Needed: updating the module, updating the admin dashboard, updating Calypso Blue

I'd like to see as much of the plugin-side work in for the October 10th release to provide buffer before WP 6.4's expected ship date of Nov 7 (which would also be the day of a Jetpack release).

I'm open to thoughts if we should just rip it out or discontinue with WP 6.4, etc. 

Internal reference: pdWQjU-wV-p2
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/33039
- [ ] https://github.com/Automattic/jetpack/pull/33030
- [ ] https://github.com/Automattic/jetpack/issues/33168
- [ ] https://github.com/Automattic/jetpack/issues/33166
- [ ] https://github.com/Automattic/jetpack/issues/33169
- [ ] https://github.com/Automattic/jetpack/issues/33167
- [ ] https://github.com/Automattic/jetpack/issues/33171
- [ ] https://github.com/Automattic/jetpack/pull/36155/
```

**Comment by jeherve** [comment]
This can now be closed, since the feature is no longer in the Jetpack plugin as of https://github.com/Automattic/jetpack/pull/33782.
