### ISSUE TITLE
Blocks: Switch all Production blocks to be registered via their block.json file

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33174]
Now that:

- we have `block.json` files for all our blocks (see #32508)
- we can register a block via that metadata (see #32697)

Let's switch all our Production blocks to using those `block.json` files.

```[tasklist]
### Tasks
- [ ] #33086
- [ ] https://github.com/Automattic/jetpack/pull/33573
- [ ] https://github.com/Automattic/jetpack/pull/33604
- [ ] https://github.com/Automattic/jetpack/pull/33667
- [ ] https://github.com/Automattic/jetpack/pull/33682
- [ ] https://github.com/Automattic/jetpack/pull/33689
- [ ] https://github.com/Automattic/jetpack/pull/33694
```

*******

Primary issue: #32602

Related work for Beta and Experimental blocks:

- #32815 
- #33073
