### ISSUE TITLE
AI Tiered Plans: Update upgrade interstitial to show the next tier available

### ISSUE THREAD

**Issue by lhkowalski** [Automattic/jetpack#33358]
On the MVP, the upgrade interstitial will show the details for the next plan available for purchase. This was called Linear Flow.

- When the user has a free plan, the interstitial will show the 100 requests upgrade
- When the user has the 100 requests plan, the interstitial will show the 200 requests upgrade
- When the user has the 200 requests plan, the interstitial will show the 500 requests upgrade
- When the user has the 500 requests plan, the interstitial will show the "Contact Us" call to action so it can be sent to a sales pipeline [target of the button to be defined]

The plan being purchased is the same (it's a plan created as a Upgradeable Quantity plan), so the tiers are set using a quantity value (200 requests or 200 units or 2 units, TBD) that will then reflect on the price being charged on the checkout (similar to DIFM extra pages).

---

Check the design wrap up post: p1HpG7-oR3-p2

---

This is required for the MVP.

**Comment by dhasilva** [comment]
- [x] Base component and logic [#33981]
- [x] TOS removal [#34076]
- [x] Linking the cta buttons to the right tier checkout page [p1699643698953239/1699642722.303119-slack-C054LN8RNVA] [#34177]
- [x] Show prices on different usage tiers [#34196]
- [x] Linking the "Contact us" button to the correct action [pbNhbs-8Iv-p2#comment-18831] [#34240]
- [x] Update the AI card to show "Upgrade" instead of "Manage" when the user has a limited tier [#34215]
