### ISSUE TITLE
WordPress 6.5 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33615]
WordPress 6.5 is set to release on *26 March 2024*.

- Planning: [make.wordpress.org/core/6-5](https://make.wordpress.org/core/6-5/)

Let's use this issue to keep track of anything that may come up until then.

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/issues/35622
- [ ] https://github.com/Automattic/jetpack/issues/36186
- [x] [Updates to the HTML API](https://make.wordpress.org/core/2024/03/04/updates-to-the-html-api-in-6-5/)
- [x] [Introducing Plugin Dependencies](https://make.wordpress.org/core/2024/03/05/introducing-plugin-dependencies-in-wordpress-6-5/)
- [x] [Miscellaneous developer changes](https://make.wordpress.org/core/2024/03/08/miscellaneous-developer-changes-in-wordpress-6-5/)
- [x] [Miscellaneous Editor changes in WordPress 6.5](https://make.wordpress.org/core/2024/03/09/miscellaneous-editor-changes-in-wordpress-6-5/)
- [ ] https://github.com/Automattic/jetpack/issues/36371
```

And **in a follow-up plugin release** (most likely the May release, 13.4), to give folks time to update:

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/pull/37047/
- [ ] https://github.com/Automattic/jetpack/pull/37049
- [ ] https://github.com/Automattic/jetpack/pull/37051
- [x] Consider using new prime options ([dev note](https://make.wordpress.org/core/2023/10/17/new-option-functions-in-6-4/))
- [ ] https://github.com/Automattic/jetpack/issues/35432
- [ ] https://github.com/Automattic/jetpack/pull/36318
```

Once WordPress 6.5 is the minimum required version in Jetpack, we can consider implementing the following changes:

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/issues/36317
```

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-5](https://make.wordpress.org/core/tag/dev-notes+6-5)

-------

For reference: prior art for WordPress 6.4 compat: #32865

**Comment by jeherve** [comment]
At this point this issue can be marked as closed. The remaining tasks remain opened and can be tackled independently in the future.
