### ISSUE TITLE
Jetpack: update dashboard to better match My Jetpack UX

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#33809]
The Jetpack plugin currently offers four different UX within the same navigation menu:

1. The "My Jetpack" page, developed in the My Jetpack page
1. The pages under Jetpack > Dashboard, Jetpack > Settings, Jetpack > Privacy, aka the "React dashboard", developed in `projects/plugins/jetpack/_inc/client/`
1. The About page (Jetpack > Settings > About) developed in `projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-about-page.php`
1. The old modules page under Jetpack > Settings > Modules developed in `projects/plugins/jetpack/class.jetpack-modules-list-table.php`

This makes for a fragmented experience and some potential confusion for new users. Ideally this would be simplified into a UX that would be more similar to "My Jetpack". It would better integrate with standalone Jetpack plugins too.

Related:

- p1HpG7-ojQ-p2
- pbNhbs-7IV-p2
- 82-gh-jetpack-roadmap

```[tasklist]
### Tasks to be defined during scoping
- [x] #32385
- [ ] #33802
- [ ] https://github.com/Automattic/jetpack/issues/33881
- [ ] https://github.com/Automattic/jetpack/issues/31969
- [ ] https://github.com/Automattic/jetpack/issues/31951
```

**Comment by jeherve** [comment]
Closing in favor of https://github.com/Automattic/jetpack-roadmap/issues/82, since most tasks here have been handled but the idea remains.
