### ISSUE TITLE
Boost: Update e2e tests to test all modules

### ISSUE THREAD

**Issue by dilirity** [Automattic/jetpack#33877]
Tests need a revision. We're not testing the newer modules we added over the past few months.

Tests missing:
- Concatenate JS
- Concatenate CSS
- Image CDN
- Image Guide
- Image Size Analyzer
- Page Cache
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/36668
- [ ] https://github.com/Automattic/jetpack/pull/36694
- [ ] https://github.com/Automattic/jetpack/pull/36716
- [x] ~Boost: Add e2e tests to Image Size Analyzer~
- [ ] https://github.com/Automattic/jetpack/pull/36501
```

**Comment by dilirity** [comment]
This feels overwhelming and needs to be broken down into smaller, easier to handle tasks.

**Comment by thingalon** [comment]
> This feels overwhelming and needs to be broken down into smaller, easier to handle tasks.

I 100% support you creating a sub-ticket for a each feature we'd like a test for :)

**Comment by dilirity** [comment]
Yay! We now have e2e test for all modules (excluding ISA). Closing this.
