### ISSUE TITLE
Top Posts & Blog Stats: support WPCOM

### ISSUE THREAD

**Issue by kangzj** [Automattic/jetpack#34506]
```[tasklist]
### Tasks
- [ ] <strike>Resolve the stats/top-posts call for the endpoint</strike>
- [x] Boot up the endpoint on WPCOM
- [x] Register block on WPCOM
```

**Comment by Aurorum** [comment]
Would also be very cool if support for Likes is added when handling WP.com! The legacy widget allows you to display posts that have the most Likes rather than basing it on traffic, but I don't have access to a WP.com environment that would have enabled me to add this. 

Not sure how high priority that would be, but it does feel a little unideal not to match the legacy widget's features.

**Comment by Aurorum** [comment]
I tried to investigate adding Likes but I'm a little stuck, and would appreciate guidance on whether I'm missing something. Is `wpl_get_blogs_most_liked_posts()` open-source, or am I able to access it somehow? (I have an a8c proxy if that makes a difference)  

https://github.com/Automattic/jetpack/blob/79b426bb66ae25b744aff061cb1259338804791c/projects/plugins/jetpack/modules/widgets/top-posts.php#L644-L651

**Comment by jeherve** [comment]
> Boot up the endpoint on WPCOM

Done in D139308-code.

> Register block on WPCOM

PR for it is at #35866.

> Resolve the stats/top-posts call for the endpoint

I'm not quite sure what you meant by that?

**Comment by kangzj** [comment]
> Resolve the stats/top-posts call for the endpoint

@jeherve thanks for wiring it up for wpcom. The block was calling the API before, but later refactored to use php call directly, so I don't think this is valid anymore. 

https://github.com/Automattic/jetpack/pull/34479/files

**Comment by jeherve** [comment]
Reopening this issue since #38564 reverted things for that block too.

See #36141 and https://github.com/Automattic/jetpack/pull/38564#pullrequestreview-2201833129 for more discussions about it.

**Comment by Gustavo-Hilario** [comment]
The user on 850898-zen started using the Top Posts & Pages block a few weeks ago, but now it is unsupported on their site. I'm letting them know that we're still testing this block, so it's currently unavailable.

**Comment by pauljacobson** [comment]
Hi @kangzj  and @jeherve 

I have a request for an update from our customer in 9023229-zen (follow-up to 8546916-zen) in which they reported that the Blog Stats Block wasn't working on their Simple site. Has the team managed to make progress with this issue?

**Comment by susanjanec** [comment]
I landed on this ticket and wanted to check on the status to let the user know. Thanks!

**Comment by kangzj** [comment]
We don't have to capacity to look into this unfortunately. Last time I looked into it,  [the stats API call fails for Simple sites](https://github.com/Automattic/jetpack/issues/36141#issuecomment-1975376558). I guess it might be a good task for @Automattic/jetpack-vulcan ?

**Comment by kangzj** [comment]
Asked in Slack: p1743129864485969-slack-CDLH4C1UZ

**Comment by kangzj** [comment]
Posting the comment in Slack here for visibility:


> It happens for two endpoints:
> 
> - /wpcom/v2/{site-id}/blog-stats
> - /wpcom/v2/{site-id}/top-posts
> 
> Both endpoints leverage the stats package to get the required data (e.g. blog stats: [jetpack code](https://github.com/Automattic/jetpack/blob/1c89f68103ef7353e6f59e43b1af1bc0bb98b391/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-blog-stats.php#L64), wpcom location - GHE-Automattic/wpcom/blob/trunk/wp-content/rest-api-plugins/jetpack-endpoints/class-wpcom-rest-api-v2-endpoint-blog-stats.php), meaning a v2 api is calling v1.1 in essence, which is forwarded by WPCOM_API_Direct. The request is sent from blocks in editor. On simple sites, it's failing - I debugged the request, the error is 404 because none of v1.1 endpoints are registered.
> 
> Steps to reproduce:
> 
> - Remove the condition to register the block here - GHE - Automattic/wpcom/blob/7f0e4c3bf365e7f72ff034309955580648f952b4/wp-content/mu-plugins/jetpack-plugin/moon/extensions/blocks/blog-stats/blog-stats.php#L24
> - Sandbox a simple site and public-api.wordpress.com
> - Create a new post
> - Insert Blog Stats block
> - Inspect blog-stats request in network manager
> - 
> 
> It is exactly the same case for the Top Posts block.


cc/ @fgiannar

**Comment by kangzj** [comment]
Blog Stats block is now available for simple sites.

**Comment by kangzj** [comment]
Top posts block is now available for Simple sites
