### ISSUE TITLE
Block discoverability: update module status to use Redux Store

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#34595]
This project is a follow-up to #32401.

Now that we've implemented #33397, we now can work towards replacing current logic inside `useModuleStatus` utilizing the store. This would allow to a more consistent state within the page.

**This would improve the user experience when first loading blocks that are linked to inactive modules.**

Internal reference: pf5801-lr-p2
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/34588
- [ ] https://github.com/Automattic/jetpack/issues/34590
- [ ] https://github.com/Automattic/jetpack/issues/34589
- [ ] https://github.com/Automattic/jetpack/issues/34603
```

**Comment by jeherve** [comment]
This should now be good to be closed. Here are some important references / discussions on that project:

- pf5801-lr-p2
- pf5801-oD-p2
