### ISSUE TITLE
Sharing Block: TODO list for v1 release

### ISSUE THREAD

**Issue by andrii-lysenko** [Automattic/jetpack#34726]
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/issues/34727
- [ ] https://github.com/Automattic/jetpack/issues/34784
- [ ] https://github.com/Automattic/vulcan/issues/142
- [ ] https://github.com/Automattic/jetpack/issues/34621
- [ ] https://github.com/Automattic/jetpack/issues/35141
- [ ] https://github.com/Automattic/jetpack/issues/35168
- [ ] https://github.com/Automattic/jetpack/issues/35047
```
