### ISSUE TITLE
[Boost] Move styles into module stylesheets

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35010]
**Note:** this is a fiddly task with lots of little bits. I recommend against trying to tackle it in one giant PR. Make small quick PRs over time.
**Another note:** this is not a blocker to release.

We have styles spread across global CSS files and module files. We've decided that moving forward module files are the way to go for all but the most global-of-global things.

Here are some examples of things that can be moved into module styles:
- https://github.com/Automattic/jetpack/pull/34599#discussion_r1434993949
- https://github.com/Automattic/jetpack/pull/34599#discussion_r1434994431
- https://github.com/Automattic/jetpack/pull/34599#discussion_r1434994715

But there are more.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/35156
- [ ] https://github.com/Automattic/jetpack/pull/35516
- [ ] https://github.com/Automattic/jetpack/issues/41373
- [ ] https://github.com/Automattic/jetpack/issues/41369
- [ ] https://github.com/Automattic/jetpack/issues/41370
```

**Comment by haqadn** [comment]
I am attempting this in #35104. However, the ISA styles are too tangled to modularize without risking UI bugs.

**Comment by thingalon** [comment]
> I am attempting this in #35104. However, the ISA styles are too tangled to modularize without risking UI bugs.

Don't feel pressure to solve 100% of all cases in one go. It's ok for this to take multiple smaller PRs, and it's ok to enlist help from @pyronaur (who built the IG UI) to sort out some of the tricker cases.

**Comment by dilirity** [comment]
After #35156 gets merged, the only styles left would be ISA.

**Comment by dilirity** [comment]
I'm splitting moving ISA components into two parts, as the first PR has gotten quite big. Moving some of the styles would require more work.

**Comment by dilirity** [comment]
@haqadn great work bringing this to the finish line!

Closing this!
