### ISSUE TITLE
[Boost] Build a UI for the Boost Cache MVP

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#35054]
Part of the upcoming Boost Cache project: pc9hqz-2rA-p2
Discussion on the UI here: pc9hqz-2sW-p2

Build a UI for the new Boost Cache feature MVP. The MVP is very basic, and should only include the following features in its UI:

- An on/off toggle, like the rest of the features on the Boost dashboard.
- One configuration setting that appears when the feature is enabled: an option to exclude pages from the cache. Either by full URL or by entering a partial URL or RegExp pattern to match.
- A notice we can show on the dashboard if we don't believe the feature can be enabled due to their hosting provider. e.g.:

> Your site has an empty `advanced-cache.php` file installed. This is a common practise by hosting providers to indicate that users on their platform should not install their own cache."

Additionally, it's worth thinking about changes to our existing upgrade prompt(s) on the Boost page for free users to indicate that a Page Cache is available upon upgrade. At the moment we have notices next to relevant features - but Boost Cache is a feature that will not exist at all in the free version.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/35568
- [ ] https://github.com/Automattic/jetpack/issues/35673
- [ ] https://github.com/Automattic/jetpack/pull/35729
- [ ] https://github.com/Automattic/jetpack/issues/35783
```

**Comment by jsnmoon** [comment]
I placed this back on Jetpack Projects as a "Design Only" task [per this comment](https://github.com/Automattic/jetpack-roadmap/issues/921#issuecomment-1906507957).

**Comment by jsnmoon** [comment]
Relevant quote from @thingalon in https://github.com/Automattic/jetpack-roadmap/issues/921#issuecomment-1897662440: 

> I've created a P2 discussing the open questions about design for this project here: pc9hqz-2sW-p2

**Comment by dilirity** [comment]
Closing this, as all tasks are done and beta has been rolled out for testing.
