### ISSUE TITLE
Masterbar: refactor feature and move to mu-wpcom

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35469]
Let's talk about the Masterbar module and its future in the Jetpack plugin and in the mu-wpcom plugin.

### History

**Improves the experience for Jetpack authors when they've transferred their WordPress site from WordPress.com to a self-hosted plan by providing a similar experience to the front-end navigation on WordPress.com.**

- Introduced in #6413
- PT: p3fqKv-4kf-p2

### Current features

The feature currently lives here on WoA and self-hosted sites:
https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar.php

It is:

- Not enabled by default on self-hosted sites
- Force-enabled on WoA sites via wpcomsh

On WordPress.com Simple sites, it is loaded differently:

fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Sznfgreone.cuc%3Se%3Q494pr4o9%233-og

It includes the following features:

The basic feature set is a replacement for the core admin bar, defined in `projects/plugins/jetpack/modules/masterbar/masterbar/class-masterbar.php`. This custom admin bar is extended with side-panels (that we talked about removing in #35199)

We extend that basic feature set with other features that are enabled on WoA and/or simple sites:

- “nav-unification”, i.e. an override of the navigation menu on all sites. This is being actively worked on as part of the Untangling Calypso project.
    - https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar.php#L45-L47
- Inline Help: an icon appearing on almost all wp-admin pages and leading you to WordPress.com/help.
    - https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar/inline-help/class-inline-help.php#L3
- Nudges to purchase a WordPress.com Plan to be able to customize CSS on your site.
    - https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar/nudges/bootstrap.php#L3
- Admin Color Schemes, an attempt to unify admin color scheme across WordPress.com sites and Calypso. This feature is about to change, as part of the Untangling Calypso project.
    - pfsHM7-1C-p2
    - https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar/admin-color-schemes/class-admin-color-schemes.php#L3
- User Profile customizations so site owners do not inadvertently make changes to their local account on a WoA site.
    - https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar/profile-edit/bootstrap.php#L3
- Posts_List_Page_Notification, a way to fix this issue -> https://github.com/Automattic/wp-calypso/issues/52692.
    - https://github.com/Automattic/jetpack/blob/5b320dc39fc6a437b6482757c9a68930f1f99138/projects/plugins/jetpack/modules/masterbar/wp-posts-list/bootstrap.php#L3
    - This feels like something that should / could be confusing to any WordPress user, so maybe that should be something that could be tackled in Core? Although with the move to FSE, this is probably not as much of an issue as it once was.

## In the future

I do not think any of those features belong in the Jetpack plugin. At a time it made sense to ship those features in Jetpack because Jetpack was a good delivery mechanism for both WordPress.com simple and WoA sites. We now have the mu-wpcom plugin for that.

With that in mind, we could aim to do the following:

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/issues/36916
- [ ] https://github.com/Automattic/jetpack/issues/36917
- [ ] https://github.com/Automattic/jetpack/issues/36918
- [ ] https://github.com/Automattic/jetpack/issues/37702
- [ ] https://github.com/Automattic/vulcan/issues/446
- [ ] https://github.com/Automattic/vulcan/issues/448
- [ ] https://github.com/Automattic/vulcan/issues/449
- [x] In the Masterbar package, remove the side-panels as we started doing in #35199
- [x] In a future Jetpack release, stop requiring the Masterbar package and remove the module
```

*******************

Internal references:

- pe7F0s-1Fw-p2

**Comment by jeherve** [comment]
@kraftbj What do you think about this deprecation plan overall? Would you change / add anything in that process?

**Comment by kraftbj** [comment]
Thinking out loud, the move to the masterbar package is mainly a transitionary step. Do we actually expect to use need the masterbar functionality in other places? Would it make sense to introduce, say, a `jetpack-code-transition` package that we use for these things that are _moving_ to different places and not being embedded into multiple products?

Just thinking about the overhead of having to spin up Packagist accounts, the extra repos, etc.

The only consideration otherwise is coordination with Loop to ensure they can move forward with what they'd like to land for WC Asia without being impaired.

**Comment by jeherve** [comment]
> Do we actually expect to use need the masterbar functionality in other places?

I don't think so. It's really more of a need for the transition, not after. I'd be opened to a package that we would then deprecate, or a special package like you mention. Both are fine by me. I don't think the overhead of creating a new package is that big, to be honest.

> The only consideration otherwise is coordination with Loop to ensure they can move forward with what they'd like to land for WC Asia without being impaired.

Right. Personally I think it'd be more realistic to wait until WC Asia for the move. The Masterbar is modified daily right now, so we'd be bottlenecks if we decided to start a move now. 
We can get started with the basic package though.

**Comment by fgiannar** [comment]
PT: pfwV0U-3U-p2

All the related tasks have now been completed.
