### ISSUE TITLE
Jetpack Connection: Improve screen reader experience

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#35478]
Going through the Jetpack Connection with a screen reader isn't straightforward. This issue lists several pain points a screen reader user might encounter.

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/issues/35479
- [ ] https://github.com/Automattic/jetpack/issues/35480
- [ ] https://github.com/Automattic/jetpack/issues/35481
- [ ] https://github.com/Automattic/jetpack/issues/35482
- [ ] https://github.com/Automattic/jetpack/issues/35483
- [ ] https://github.com/Automattic/jetpack/issues/35484
- [ ] https://github.com/Automattic/jetpack/issues/35485
- [ ] https://github.com/Automattic/jetpack/issues/35486
- [ ] https://github.com/Automattic/jetpack/issues/35487
- [ ] https://github.com/Automattic/jetpack/issues/35488
- [ ] https://github.com/Automattic/jetpack/issues/35489
- [ ] https://github.com/Automattic/jetpack/issues/35490
- [ ] https://github.com/Automattic/jetpack/issues/35491
```

******

Initial post: p1HpG7-qVW-p2
PT: TBD
