### ISSUE TITLE
Jetpack: remove full-screen modal components and tooling

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#35603]
In #34768, we removed the full-screen modal that appeared on the plugins screen when you first activated the Jetpack plugin.

Now that the modal isn't used anymore, we should be able to remove its elements from the codebase.

```[tasklist]
### Tasks
- [ ] Remove `projects/plugins/jetpack/class-jetpack-connection-widget.php`
- [ ] Remove `jetpack_connection_banner_ab` from list of synced options.
- [ ] Remove `projects/plugins/jetpack/class-jetpack-recommendations-banner.php`
- [ ] Remove `projects/plugins/jetpack/class.jetpack-connection-banner.php`
- [ ] Remove the `jetpack_connection_banner_callback` function and where it is being hooked in `projects/plugins/jetpack/class.jetpack.php`
- [ ] Remove some of the data passed to the minimal state in `projects/plugins/jetpack/_inc/lib/admin-pages/class-jetpack-redux-state-helper.php`. (see #29566)
- [ ] Remove the `activate_dialog` method from `projects/plugins/jetpack/class.jetpack.php` (see #29566)
- [ ] Remove activation modal entry point from `projects/plugins/jetpack/tools/webpack.config.js`
- [ ] Remove activation modal entry files (`projects/plugins/jetpack/_inc/client/portals/activation-modal.jsx` and `projects/plugins/jetpack/_inc/client/activation-modal-entry.js`) and its associated SCSS file (`projects/plugins/jetpack/_inc/client/portals/activation-modal.scss`)
- [ ] Remove `_inc/jetpack-connection-banner.js`
- [ ] Remove `_inc/connect-button.js`
- [ ] Remove `css/jetpack-connect.css`
- [ ] Add the filters from the files we're removing to the `deprecated_hooks` in `projects/plugins/jetpack/class.jetpack.php`
```
