### ISSUE TITLE
Contact Form: deprecate module code

### ISSUE THREAD

**Issue by monsieur-z** [Automattic/jetpack#35652]
The Contact Form module code has been brought over to the Jetpack Forms package. It is time to deprecate the module codebase (the module itself will technically still exist).

Project thread: pf5801-Aj-p2

```[tasklist]
## Step 1
- [ ] https://github.com/Automattic/jetpack/issues/35654
- [ ] https://github.com/Automattic/jetpack/issues/35653
- [ ] https://github.com/Automattic/jetpack/issues/35655
- [ ] https://github.com/Automattic/jetpack/issues/35656
- [ ] https://github.com/Automattic/jetpack/issues/35657
```

```[tasklist]
## Step 2
- [ ] https://github.com/Automattic/jetpack/issues/35658
- [ ] https://github.com/Automattic/jetpack/issues/35659
- [ ] https://github.com/Automattic/jetpack/issues/35660
- [ ] https://github.com/Automattic/jetpack/issues/35661
- [ ] https://github.com/Automattic/jetpack/issues/35662
- [ ] https://github.com/Automattic/jetpack/issues/35663
- [ ] https://github.com/Automattic/jetpack/issues/35664
```
