### ISSUE TITLE
Subscribe block: button-only design

### ISSUE THREAD

**Issue by pkuliga** [Automattic/jetpack#35708]
It would be useful for placing the Subscribe block into the navigation.

![Image](https://github.com/Automattic/jetpack/assets/4068554/072b0cc4-0ee1-44e7-bbeb-5189e713fedc)

After the button is clicked we should open a modal to get the user email.

### TODO

- [x] Add button-only style to the Subscribe block and open the modal to get an email when the button is clicked https://github.com/Automattic/jetpack/pull/37464
- [x] If we have the user email (he is logged in or sth) we should use the normal flow
- [x] Implement the modal for getting the email from the user (@crisbusquets we need a design for this one) D148314-code
- [x] standardize the existing modals D138483-code

**Comment by simison** [comment]
FYI @Automattic/gold that we're looking into this and will need to do some changes in the modal.

**Comment by crisbusquets** [comment]
## Flow
@pkuliga here's the flow. I've added how it would look like in Gutenberg and in a post.
Figma file: yJiLZt1ozJqMltHHQxR4Gc-fi-4392_12514

![subscribe-block-flow](https://github.com/Automattic/jetpack/assets/25607244/38eff4da-7c87-4cf1-b828-b5a7339c165e)


## Modals update
To fit the subscribe block I've updated all the modals' width and padding to have a consistent and standardized version. Now it uses an 8pt grid for all spacings.

See current/proposal:

![compare-modals](https://github.com/Automattic/jetpack/assets/25607244/e001c2b7-9ee6-4691-84c4-49e078f58029)



Specs: yJiLZt1ozJqMltHHQxR4Gc-fi-4392_12250

**Comment by crisbusquets** [comment]
After discussing it with @pkuliga, we've updated the padding-top for the header.

Here's the updated Figma file with all the specs:
- Subscribe modal: yJiLZt1ozJqMltHHQxR4Gc-fi-4416_3255
- Tiers modal: yJiLZt1ozJqMltHHQxR4Gc-fi-4416_3412
- Payment form modal: yJiLZt1ozJqMltHHQxR4Gc-fi-4416_3944
- Categories modal: yJiLZt1ozJqMltHHQxR4Gc-fi-4416_4589

**Comment by simison** [comment]
Modal padding changes are now live with D138483-code

Next;
- Button only design, in progress https://github.com/Automattic/jetpack/pull/33921
- Supporting asking email in the modal

**Comment by pkuliga** [comment]
Closing this one since it was resolved here: https://github.com/Automattic/jetpack/pull/37341
