### ISSUE TITLE
Newsletter: Welcome overlay

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/jetpack#36208]
### Context
Suggested by @mtias during the Design Division Meetup.
Related to p1HpG7-rrt-p2 (I already added the option to Jetpack Settings > Newsletter).

### What
Currently only the [Lettre theme](https://wordpress.org/themes/lettre/) has a "Welcome overlay" to get more subscribers:

![Image](https://github.com/Automattic/jetpack/assets/25607244/f672ad15-ad54-497d-9e71-8a1e435694f0)

Just as we already do with the subscribe modal (that appears when scrolling), we should enable any theme to have it.

It should include:

- [ ] Avatar
- [ ] Heading
- [ ] Description
- [ ] Subscribe block
- [ ] Icon to dismiss the overlay on the top 

By default, we could reuse the same text that appears on the subscriber modal, but users should be able to edit it in the Site Editor (WDYT @simison ?).

### TODO

- [x] Overlay with editable template https://github.com/Automattic/jetpack/pull/37372
- [x] Integration with existing subscription flow https://github.com/Automattic/jetpack/pull/37372
- [x] Jetpack Newsletter settings toggle https://github.com/Automattic/jetpack/pull/37433
- [x] add option to sync (WPCOM repo) D149362-code
- [x] Calypso Newsletter settings toggle https://github.com/Automattic/wp-calypso/pull/91089
- [x] Initialize the overlay on Dotcom D149890-code
- [x] Add more generic styles to the Subscription flow modal D148978-code
- [ ] #37621

**Comment by crisbusquets** [comment]
Wrap-up post:
p1HpG7-so7-p2

**Comment by pkuliga** [comment]
Closing this one since all related tasks have been done. Further work will continue under dedicated issues.
