### ISSUE TITLE
Subscription Site: Add Subscriber Login block into the navigation

### ISSUE THREAD

**Issue by pkuliga** [Automattic/jetpack#36266]
Related to peKye1-EA-p2

We would like to hook the Subscriber Login block into the navigation.

### TODO
- [x] add the toggle to the jp Newsletter Settings https://github.com/Automattic/jetpack/pull/36487
- [x] hook the Subscriber Login block to the last child of the navigation when the toggle is on https://github.com/Automattic/jetpack/pull/36487
- [ ] #37597
- [x] add the toggle to the Calypso settings https://github.com/Automattic/wp-calypso/pull/90037
- [x] add the option to the Sync package and Dotcom API https://github.com/Automattic/jetpack/pull/36737 D144338-code https://github.com/Automattic/jetpack/pull/37000
- [x] link to the other template than header https://github.com/Automattic/jetpack/pull/36487#pullrequestreview-1966160803 https://github.com/Automattic/jetpack/pull/36717

**Comment by pkuliga** [comment]
Closing this one since the feature was released. Further work on it would be done under separate issues.
