### ISSUE TITLE
Boost: 3.1.1 checklist

### ISSUE THREAD

**Issue by thingalon** [Automattic/jetpack#36340]
We need a post on our main P2 - linked from the sidebar which documents a checklist for Boost releases.

Some ideas:
- [ ] - [ ] Run an internal beta;
- [ ] Prepare public documentation;
  - [ ] What documentation is that?
- [ ] Make sure links throughout the code lead to the right place in the public docs;
- [ ] Update any jetpack.com related pages;
- [ ] what else would we need for such a checklist?
