### ISSUE TITLE
WordPress 6.6 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#36721]
WordPress 6.6 is set to release on *16 July 2024*.

- Planning: [make.wordpress.org/core/6-6](https://make.wordpress.org/core/6-6/)

Let's use this issue to keep track of anything that may come up until then.

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/pull/37962
- [ ] https://github.com/Automattic/jetpack/pull/37819
- [ ] https://github.com/Automattic/jetpack/pull/37949
- [ ] https://github.com/Automattic/jetpack/issues/38031
- [ ] https://github.com/Automattic/jetpack/issues/38081
```

And **in the next plugin release** in August , to give folks time to update:

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/pull/38382
- [ ] https://github.com/Automattic/jetpack/pull/38386
- [ ] https://github.com/Automattic/jetpack/issues/36317
- [ ] https://github.com/Automattic/jetpack/pull/36188
- [ ] https://github.com/Automattic/jetpack/issues/36844
- [ ] https://github.com/Automattic/jetpack/issues/37713
- [ ] https://github.com/Automattic/jetpack/issues/37951
- [ ] https://github.com/Automattic/jetpack/issues/38027
- [ ] https://github.com/Automattic/jetpack/issues/38029
- [ ] https://github.com/Automattic/jetpack/issues/38405
- [x] [Miscellaneous developer changes in WordPress 6.6](https://make.wordpress.org/core/2024/06/25/miscellaneous-developer-changes-in-wordpress-6-6/)
- [x] [Updates to the HTML API in 6.6](https://make.wordpress.org/core/2024/06/24/updates-to-the-html-api-in-6-6/)
- [x] [Miscellaneous Editor changes in WordPress 6.6](https://make.wordpress.org/core/2024/06/24/miscellaneous-editor-changes-in-wordpress-6-6/)
- [x] [Internationalization improvements in 6.6](https://make.wordpress.org/core/2024/06/24/i18n-improvements-6-5-performant-translations-2/)
- [x] [Section Styles](https://make.wordpress.org/core/2024/06/24/section-styles/)
```

Once WordPress 6.6 is the minimum required version in Jetpack, we can consider implementing the following changes:

```[tasklist]
- [ ] Remove backwards-compatible code managed in #37713
- [ ] Support any changes to the plugin onboarding flow ([trac ticket](https://core.trac.wordpress.org/ticket/61040))
- [ ] https://github.com/Automattic/jetpack/issues/38296
```

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-6](https://make.wordpress.org/core/tag/dev-notes+6-6)

You can also consult the 1X5DEhafI9pVhddNYNHUFFSIpsl1t2b2swgr1nmsmEFE-gdoc for the release.

-------

For reference: prior art for WordPress 6.5 compat: #33615
