### ISSUE TITLE
Google Analytics: deprecate feature

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#36920]
Let's talk about the Google Analytics feature and its future in the Jetpack plugin and in the mu-wpcom plugin.

### History

**Set up Google Analytics without touching a line of code.**

This happens via Calypso Blue only:

<img width="1481" alt="image" src="https://github.com/Automattic/jetpack/assets/426388/3f3bf2f7-4da3-44c4-b6c0-337ff118856f">

It was introduced in #5603

### Current features

The feature currently lives here, and is used on WordPress.com and self-hosted:
https://github.com/Automattic/jetpack/blob/6438a55e74ce512ad33b10f34e5b92e9b368c010/projects/plugins/jetpack/modules/google-analytics.php#L1

On WordPress.com Simple, the feature is loaded differently and gated to starter plans and above:
fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Snanylgvpf.cuc%3Se%3Qro76o7oo-og

The feature is not enabled by default on self-hosted sites.

We ship 2 different versions of Google Analytics:

- For folks using WooCommerce and having toggled an option in Calypso Blue, we load `Jetpack_Google_Analytics_Universal`. This class includes extra tracking code added to shopping events / pages.
- For most folks, we load `Jetpack_Google_Analytics_Legacy`.

## In the future

I do not think any of those features belong in the Jetpack plugin at this time. At a time it made sense to ship those features in Jetpack because Jetpack was a good delivery mechanism for both WordPress.com simple and WoA sites. We now have the mu-wpcom plugin for that.

With that in mind, we could aim to do the following:

```[tasklist]
- [x] Introduce a Google Analytics package
- [x] Copy all code from the module to the new package
- [x] Require the package in both the Jetpack plugin and the mu-wpcom plugin
- [x] Update WordPress.com Simple to load the code from there.
- [x] Update Calypso so the interface supports the mu-wpcom plugin
- [x] Create a plugin, hosted only on GitHub, clearly marked as non-maintained, that loads the package. See https://github.com/automattic/minileven for an example.
- [x] Add deprecation notice displayed on self-hosted sites using the Google Analytics module. Point towards support doc explaining how to install the new plugin if necessary.
- [x] In a future Jetpack release, stop loading Google Analytics features from the Jetpack module and display notice that the feature is no longer active.
- [x] In a future Jetpack release, stop requiring the Google Analytics package and remove the module
- [ ] https://github.com/Automattic/vulcan/issues/315
- [ ] https://github.com/Automattic/vulcan/issues/308
- [ ] https://github.com/Automattic/vulcan/issues/304
- [ ] https://github.com/Automattic/vulcan/issues/303
- [ ] https://github.com/Automattic/vulcan/issues/401
- [ ] https://github.com/Automattic/vulcan/issues/359
- [ ] https://github.com/Automattic/vulcan/issues/314
- [ ] https://github.com/Automattic/vulcan/issues/313
- [ ] https://github.com/Automattic/vulcan/issues/312
- [ ] https://github.com/Automattic/vulcan/issues/366
- [ ] https://github.com/Automattic/jpop-quill/issues/271
- [ ] https://github.com/Automattic/vulcan/issues/457
```

*******************

Internal references:

- Discussion: p1HpG7-rZc-p2
- PT: pfwV0U-4g-p2

**Comment by sergeymitr** [comment]
The project is completed, the final status update is here: pfwV0U-4g-p2#comment-361
