### ISSUE TITLE
General: compatibility with PHP 8.3

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#37173]
The Core WordPress team is still working on PHP 8.3 compatibility [here](https://core.trac.wordpress.org/ticket/59231). While there are still things to change in Core to ensure full compatibility, we can also work on compatibility within the Jetpack plugins.

For a better view of WordPress's PHP compatibility and support, you can refer to [this page](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/).

- [x] https://github.com/Automattic/jetpack/pull/34312
- [x] https://github.com/Automattic/jetpack/pull/34346
- [x] https://github.com/Automattic/jetpack/pull/36392
- [x] https://github.com/Automattic/jetpack/issues/37172

--------------

For reference: PHP 8.2 compatibility was tracked in https://github.com/Automattic/jetpack/issues/27927
