### ISSUE TITLE
AI Assistant:  Refactor Form extension to new structure

### ISSUE THREAD

**Issue by renatoagds** [Automattic/jetpack#37590]
ref pe4Cmx-2jr-p2#fourth-step
```[tasklist]
### Tasks
- [x] Support Toolbar button to open input directly instead Dropdown
- [x] Support children items to trigger input from parent
- [x] Test suggestion handling
- [ ] Update UI to fit in Form block
```
