### ISSUE TITLE
Janitorial: drop support for PHP 7.0 and 7.1

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#38296]
https://make.wordpress.org/core/2024/04/08/dropping-support-for-php-7-1/

```[tasklist]
### Tasks
- [ ] https://github.com/automattic/jetpack/pull/38356
- [ ] https://github.com/Automattic/jetpack/pull/40147
- [x] Remove CI checks for PHP 7.0-
- [x] Revert changes to `.github/files/phpcompatibility-dev-phpcs.xml` (see https://github.com/Automattic/jetpack/pull/36673)
- [x] Address warnings such as #38226
- [ ] https://github.com/Automattic/jetpack/pull/40174
- [ ] https://github.com/Automattic/jetpack/pull/40200
```

******

Epic: #36721

**Comment by jeherve** [comment]
@tbradsha I see you've started working on this in #40147; Thank you! I've consequently assigned this issue to you.
