### ISSUE TITLE
WordPress 6.7 compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#38902]
WordPress 6.7 is set to release on *November 12, 2024*.

- Planning: [make.wordpress.org/core/6-7](https://make.wordpress.org/core/6-7/)

Let's use this issue to keep track of anything that may come up until then.

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/issues/39785
- [ ] https://github.com/Automattic/jetpack/pull/39841
- [ ] https://github.com/Automattic/jetpack/issues/39823
- [x] Updates to user-interface components in WordPress 6.7 ([dev note](https://make.wordpress.org/core/2024/10/18/editor-components-updates-in-wordpress-6-7/))
- [x] Miscellaneous Block Editor Changes in WordPress 6.7([dev note](https://make.wordpress.org/core/2024/10/20/miscellaneous-block-editor-changes-in-wordpress-6-7/))
- [x] Updates to Block Hooks in WordPress 6.7 ([dev note](https://make.wordpress.org/core/2024/10/21/updates-to-block-hooks-in-wordpress-6-7/))
- [x] Internationalization improvements in 6.7 ([dev note](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/))
```

And **in the next plugin release** in December , to give folks time to update:

```[tasklist]
- [ ] https://github.com/Automattic/jetpack/pull/40146
- [x] General: remove backwards-compatible code for versions < 6.6
- [ ] https://github.com/Automattic/jetpack/issues/37713
- [ ] https://github.com/Automattic/jetpack/issues/38296
```

Once WordPress 6.6 is the minimum required version in Jetpack, we can consider implementing the following changes:

```[tasklist]
- [x] Remove backwards-compatible code managed in #37713
- [ ] Support any changes to the plugin onboarding flow ([trac ticket](https://core.trac.wordpress.org/ticket/61040))
- [ ] https://github.com/Automattic/jetpack/issues/38296
```

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-7](https://make.wordpress.org/core/tag/dev-notes+6-7)

We can also follow the source of truth: 14vpmSQiOIpgQsUwMvvbqsub28dqxZeBALfrbGyKEamM-gdoc

-------

For reference: prior art for WordPress 6.6 compat: #36721

**Comment by coder-karen** [comment]
I think we can close this one out - the only remaining task is 'Support any changes to the plugin onboarding flow', but it seems like that is an ongoing discussion?

**Comment by jeherve** [comment]
Yup, let's close for now.
