### ISSUE TITLE
Connection flows: improve the plugin experience for non-admins

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#39697]
Non-admins currently get a sub-par experience when navigating Jetpack wp-admin screens or trying to use Jetpack features. Let's improve the experience for them whenever possible.

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/39081
- [ ] https://github.com/Automattic/jetpack/issues/34535
- [ ] https://github.com/Automattic/jetpack/issues/38335
```

**Comment by manzoorwanijk** [comment]
Is this still relevant?
