### ISSUE TITLE
WordPress 6.8 Compatibility

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#39818]
WordPress 6.8 is set to release on *April 15, 2025*.

- Planning: [make.wordpress.org/core/6-8](https://make.wordpress.org/core/6-8/)

Let's use this issue to keep track of anything that may come up until then.

- [x] Update our tested up to: https://github.com/Automattic/vulcan/issues/745
- [ ] https://github.com/Automattic/jetpack/issues/40040
- [x] https://github.com/Automattic/jetpack/issues/42507
- [x] https://github.com/Automattic/jetpack/issues/42395
- [x] https://github.com/Automattic/jetpack/issues/42421
- [x] https://github.com/Automattic/jetpack/issues/42579
- [x] https://github.com/Automattic/jetpack/issues/42577 and https://github.com/Automattic/jetpack/issues/42575

And **in the next plugin release* , to give folks time to update:

- [x]  https://github.com/Automattic/jetpack/pull/43192
- [x]  https://github.com/Automattic/jetpack/pull/43246

Once WordPress 6.7 is the minimum required version in Jetpack, we can consider implementing the following changes:

- [x] https://github.com/Automattic/jetpack/issues/39921
- [x] https://github.com/Automattic/jetpack/issues/39922
- [x] https://github.com/Automattic/jetpack/issues/39924
- [ ] https://github.com/Automattic/jetpack/issues/39853

In addition to the above, we can follow the dev-notes that will drop here about the release:
[make.wordpress.org/core/tag/dev-notes+6-8](https://make.wordpress.org/core/tag/dev-notes+6-8)

We can also follow the source of truth: **TBD*

-------

For reference: prior art for WordPress 6.7 compat: #38902
