### ISSUE TITLE
Audit Jetpack blocks for contentOnly 

### ISSUE THREAD

**Issue by annezazu** [Automattic/jetpack#40040]
Similar to the work being done in [Core to audit blocks for the new Write mode](https://github.com/WordPress/gutenberg/issues/65778) and contentOnly capability, I wanted to kick off an issue to do the same for Jetpack blocks as they are greatly embedded on WordPress.com and in the wider WordPress ecosystem and it would be ideal for these blocks to be prepared for this feature sooner rather than later. As a reminder, contentOnly within Patterns seeks to offer a simplified editing experience where the focus is on content related changes with only section level styling options available. 

For more information:

- https://developer.wordpress.org/news/2024/11/05/how-to-add-content-only-editing-support-to-a-block/
- https://github.com/WordPress/gutenberg/issues/71517

Please add and edit this issue as you find more Jetpack blocks that need to be updated. 

### Contact Form

-  #40955

### Subscribe

- [ ] User cannot edit the placeholder text

### Contact info

- [ ] User cannot edit any field text, whether edited or not

### Paid content

- [ ] User cannot edit any buttons

### Map

- [ ] https://github.com/Automattic/jetpack/issues/40712

**Comment by jeherve** [comment]
Thanks for creating this Epic! Is there any chance you could add a bit of context about this new Write mode? I looked around a bit but couldn't find a dev note or an Epic in the Gutenberg repo, highlighting the changes and how we can adapt to it.

Thank you!

**Comment by simison** [comment]
> **Subscribe**
> User cannot edit the placeholder text

It's not possible to edit placeholder text at block canvas in any mode, but is it still available to edit via sidebar?

<img src="https://github.com/user-attachments/assets/aec83856-bca1-4e43-9124-449dd032a8e1" width="500"/>

<img src="https://github.com/user-attachments/assets/5534a739-d333-4e9d-a253-f3a8c2638a05" width="250"/>

**Comment by annezazu** [comment]
>Thanks for creating this Epic! Is there any chance you could add a bit of context about this new Write mode? I looked around a bit but couldn't find a dev note or an Epic in the Gutenberg repo, highlighting the changes and how we can adapt to it.

Here's the broader vision: https://github.com/WordPress/gutenberg/issues/60021 There currently isn't a dev note in place as it's not landing for 6.7 but planned for 6.8. Check out the in progress tutorial for the official dev blog for now though: https://github.com/WordPress/developer-blog-content/issues/303

>It's not possible to edit placeholder text at block canvas in any mode, but is it still available to edit via sidebar?

I'm referring to when you are in Write mode :) That option goes away.

**Comment by jeherve** [comment]
> Here's the broader vision: [WordPress/gutenberg#60021](https://github.com/WordPress/gutenberg/issues/60021) There currently isn't a dev note in place as it's not landing for 6.7 but planned for 6.8. Check out the in progress tutorial for the official dev blog for now though: [WordPress/developer-blog-content#303](https://github.com/WordPress/developer-blog-content/issues/303)

Thanks, that helps!

May I suggest adding the "[Feature] Write mode" label to that issue? I think I missed it because I was using the label to filter through issues.

**Comment by annezazu** [comment]
Done! Thanks for calling that out.

**Comment by jeherve** [comment]
@annezazu This may be a stupid question, but how is this new method supposed to work? I read about it, then played with it a bit and it seems I cannot really add any blocks when in Write mode. Would I add blocks when in Design mode, and then go to Write mode and update them? And in our audit, we would want to make sure all our blocks, once added, can still have their contents (such as placeholders or any field) be editable when in Write mode?

If we take the Contact Form feature for example, what would the expected workflow be? Would I be expected to use Write Mode when creating or editing a form? If so, what would be the expected steps? Add the parent block in design mode, add the child blocks (each field) in design mode, and then enter Write mode and change the contents of the different fields I created?

**Comment by annezazu** [comment]
Not a stupid question at all and part of the "dance" we're trying to figure out in Core. 

>I read about it, then played with it a bit and it seems I cannot really add any blocks when in Write mode. Would I add blocks when in Design mode, and then go to Write mode and update them? 

Yes, as it stands, you cannot add new blocks in this mode and you'd have to switch between them. There is a very early convo happening around the possibility of adding inner blocks in the future [Add new mode to contentOnly locking to allow insertion of new inner blocks](https://github.com/WordPress/gutenberg/issues/52018#top). This would be great to chime in on if you think it would benefit Jetpack. 

>And in our audit, we would want to make sure all our blocks, once added, can still have their contents (such as placeholders or any field) be editable when in Write mode?

All of the blocks that makes sense. For Core, for example, we're having to reconsider what this mode looks like when it comes to both [navigation](https://github.com/WordPress/gutenberg/issues/65699) and the [query loop](https://github.com/WordPress/gutenberg/issues/66614) blocks. You all might have similar use cases and can likely follow along to see how we approach things in Core. 

>If we take the Contact Form feature for example, what would the expected workflow be? Would I be expected to use Write Mode when creating or editing a form? If so, what would be the expected steps? Add the parent block in design mode, add the child blocks (each field) in design mode, and then enter Write mode and change the contents of the different fields I created?

In this case, I would think of it more as someone adds a pattern with the Jetpack contact form block in it onto a new "Contact me" page and they have this mode on. They then are trying to edit and build out the form, focused just on the copy and any high level styling options. 

On the flip side, we also need to consider someone adding this block in. Since you can't add blocks in Write mode, you can imagine someone adding it in Design mode and then later switching to Write mode in order to simplify the editing experience. Does that make sense?

Keep sharing as this is helpful feedback!

**Comment by annezazu** [comment]
To follow up, here's the [developer blog post about this contentOnly option](https://developer.wordpress.org/news/2024/11/05/how-to-add-content-only-editing-support-to-a-block/) 🥳

**Comment by flexseth** [comment]
> Similar to the work being done in [Core to audit blocks for the new Write mode](https://github.com/WordPress/gutenberg/issues/65778), I wanted to kick off an issue to do the same for Jetpack blocks as they are greatly embedded on WordPress.com and in the wider WordPress ecosystem

I've been using the Entrepreneur bundle for Jetpack CRM to test it out, having access to Gutenberg for creating better task lists would be really helpful. The [Quote Builder](https://kb.jetpackcrm.com/knowledge-base/how-do-i-create-a-quote/) uses the classic editor, it would be cool to build that with blocks but understand there may be serious UI undertakings for that to happen. The zoomed out view would be great for quotes. 

If the work is getting done, please Jetpack CRM could be looked at in the audit!

**Comment by annezazu** [comment]
[Pattern editing changes are coming to WordPress 7.0](https://make.wordpress.org/core/2026/03/15/pattern-editing-in-wordpress-7-0/). Can you all take a look at what's coming and ensure there's a plan for Jetpack? Part of this means deciding what the default experience should be, which will likely require design help.
