### ISSUE TITLE
General: compatibility with PHP 8.4

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack#40105]
The Core WordPress team is still working on PHP 8.4 compatibility [here](https://make.wordpress.org/core/2024/11/07/getting-ready-for-php-8-4-some-code-changes-landing-in-6-7/). While there are still things to change in Core to ensure full compatibility, we can also work on compatibility within the Jetpack plugins.

For a better view of WordPress's PHP compatibility and support, you can refer to [this page](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/).

```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/jetpack/pull/39187
- [ ] https://github.com/Automattic/jetpack/pull/36673
- [ ] https://github.com/Automattic/jetpack/pull/40255
- [ ] https://github.com/Automattic/jetpack/pull/40253
```

--------------

For reference: PHP 8.3 compatibility was tracked in #37173

**Comment by jeherve** [comment]
@anomiex Do you think we can close this issue now, or did you have any other outstanding tasks in mind?

**Comment by anomiex** [comment]
I think we're good.

**Comment by jeherve** [comment]
Thank you for your work on this! 🥳
