### ISSUE TITLE
UI Improvements to the Map block Inspector

### ISSUE THREAD

**Issue by richtabor** [Automattic/jetpack#40718]
Minor tasks to clean up the UI in the Map block inspector

### Tasks

- [x] Change "Map Settings" to "Settings" 
- [x] Change "Show street names" to "Show labels" 
- [x] Change "Marker Color" to "Marker" 
- [ ] Update "Height in pixels" control to use the Gutenberg HeightControl control (can use the same table.  
- [x] Update "Zoom level" control to use proper range control large size, like the core/latest-comments block for example. 

### Visual 
![Image](https://github.com/user-attachments/assets/8dc675f5-d42d-4a1f-b498-8aef7f55c60d)
![Image](https://github.com/user-attachments/assets/df042d2b-9ede-43a3-9f5c-59ee7144a04d)
