### ISSUE TITLE
Update the subscription confirmation flow

### ISSUE THREAD

**Issue by richardmtl** [Automattic/jetpack#701]
The email subscriptions confirmation flow was recently updated on WordPress.com; these changes need to be ported over to Jetpack as well. This is a placeholder issue if discussion is needed for those changes.

- [x] - Blog subscriptions should inform of pending confirmations #276
- [x] - Subscriptions: Notify email-only subscribers when they have too many pending subscriptions #2278
- [x] - Subscription message for existing subscribers #5812
- [ ] - Subscriptions: Confirmation link in email gives error if logged into WP.com with different account #5407
- [x] - Subscriptions/Publicize: Provide UI to confirm sub was successfully submitted #5151
