### ISSUE TITLE
Masterbar: Updates across Calypso, WP.com, and Jetpack versions

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack#9098]
Following are screenshots of the different Masterbar menus across (left-right) Calypso, Jetpack site, WP.com (front-end or wp-admin). These are taken from a site with all custom post types enabled, and it's using the Canape theme which introduces the Food Menus CPT as well.

![masterbar-my-sites](https://user-images.githubusercontent.com/108942/37671951-785116f0-2c32-11e8-8c23-f49b14cfd234.png)
![masterbar-reader](https://user-images.githubusercontent.com/108942/37671953-788c13b8-2c32-11e8-8213-b699712e22b3.png)
![masterbar-me](https://user-images.githubusercontent.com/108942/37671956-78bb750e-2c32-11e8-82da-bfacca0836d5.png)

There are a bunch of things going on here, so I'll try to make a checklist, but feel free to update it:

**My Sites**
- [ ] #7011 (Footer and Help Icon)
- [ ] "Switch Site" is capitalized, and uses a different arrow in WP.com and Jetpack
- [ ] Text/icon color (and size?) has been changed on Calypso, needs to be changed in Jetpack/WP.com
- [ ] No upgrade banner in Jetpack
- [ ] View Site link has a white background in Jetpack, but doesn't in Calypso (same in WP.com, although this screenshot doesn't show it because that link only appears within wp-admin)
- [ ] Stats sparkline on WP.com frontend, nowhere else?
- [ ] Media item is missing from Jetpack, see #7009
- [ ] Feedback item missing from Jetpack menu, again see #7009
- [ ] Portfolio & Testimonials items are in different order in Calypso vs Jetpack
- [ ] Food Menus CPT doesn't appear in Jetpack (does appear elsewhere)
- [ ] Food Menus (perhaps all CPTs?) don't have a (default) icon in WP.com
- [ ] Ads only appears in Calypso, not in Jetpack. I haven't confirmed if it appears in WP.com because I don't have a site there with Ads enabled
- [ ] Dashboard or WP Admin link does not appear in Calypso. See https://github.com/Automattic/wp-calypso/issues/21058

**Reader**
- [ ] Conversations item missing from Jetpack
- [x] Both Automattic-only menu items ("Automattic" and "A8C Conversations") missing from Jetpack, although we can ignore that one probably.
- [ ]  Recommendations appears in Jetpack, not in the others
- [ ] Lists and Tags appear only in Calypso

**Me**
- [ ] Gravatar is much bigger for Calypso than it is for either Jetpack or WP.com
- [ ] Notification Settings label is different in Calypso vs others
- [ ] Help item appears in Jetpack/WP.com, but not in Calypso

**Comment by jeherve** [comment]
Reopening as the navigation drawers were added back in #12454
