### ISSUE TITLE
Continuous integrations tests: Refactors FTW

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack#9884]
# Refactoring CI jobs, unit test runs and improving accountability on them

#9904 is a PR for reference showing some possible implementations of the items proposed below.

## Roadmap 

* [ ] **Make all possible jobs run on PHP 7.2**
Why? PHP 7.x is at least 2.x faster than running on the default PHP 5.5 environment in most cases - #9904.
* [x] **Add handy commands for running linting and PHP 5.2 compatibility** - #9878 .
  * [x] **Document those commands** - #9878 .
  * [ ] **Enable a job for running linting against the whole codebase (ignoring unit test code) on each PR** 
Why ? Instead of running tests under PHP 5.2 we can catch a lot of things faster and improve our culture by just linting for compatibility with PHP 5.2 and returning the dev useful messages about practices.
  * [ ] **Have a pre-commit hook linting for PHP 5.2 compatibility** - #9908.
  * [ ] **Fix all PHP 5.2 compatibility issues according to PHPCompatibility ruleset** -  #9905

* [x] **Have a single job for lintinting the Jetpack Admin page** 
Why? We have two sets of test suites for testing the React based adin page.  This means consolidating `yarn test-gui` and `yarn test-client`. - #9878
    * [ ] **Make both of them run on the same environments and then saving a job**. -   #9911
* [ ] **Disable all unit test runs expect latest PHP on PRs**
Why? We need to increase visibility of feature developer's work and help them integrate in `master` faster. For this, we need to make them aware of failures once they know the failure will affect other devs. Then on `master`, we can run all the jobs, linting, and testsuites.
* [ ] **Enable all unit test jobs from php 5.2 to 7.2 for `master`**
Why ? With this we can now make use of the frightening emails that Travis is able to send. Having `master` fail for any given unit tests and making all Jetpack developers be noticed about it could increase the overal knowledge of the codebase and changes being introduced.
* [ ] **Make all developes receive notifications about failures coming from tests running on `master`**
Why ? - Explained on the previous items.
* [ ] **Make Travis set PR's status to non-passing right away** if at least one job failed
This may or may not be necessary if cutting the down the jobs per PR. right now.
* [ ] **Create a special label `Needs CI tests on all envs`**
Why? This would allow us to run all environments jobs on a single PR. Something magical like what we do with the label `Needs e2e Canary Testing`.
* [ ] **Remove unnecessary [installation of gems](https://github.com/Automattic/jetpack/blob/master/tests/run-travis.sh#L41-L42)**
Why ? - This seems unnecessary given that all of our sass related tasks are based on node packages and not CLI tools - #9904. 

Expectation:

<img width="541" alt="screen shot 2018-07-07 at 11 50 56 am" src="https://user-images.githubusercontent.com/746152/42413272-8716d7bc-81f3-11e8-946c-0db234463f1c.png">

#### What I expected

CI jobs to be more accountable and reliable for avoiding WSODs on the myriad of stacks Jetpack is deployed on.

**Comment by brbrr** [comment]
Fix all PHP 5.2 compatibility issues according to PHPCompatibility ruleset: #9905 
Add pre-commit hook for PHPCompatibility check: #9908

**Comment by abidhahmed** [comment]
> Disable all unit test runs except latest PHP on PRs
> Enable all unit test jobs from php 5.2 to 7.2 for master

Wouldn't this create more _confusion_ when things start to fail on Master? Afaik test on Master will run immediately after a PR is merged. If things were to fail there, wouldn't it just be easier if they failed in the PR itself?

**Comment by oskosk** [comment]
@brbrr Added your PRs to the main description of this issue.

@abidhahmed I started thinking on this by following an idea of emulating Jetpack having a continuous deployment "somewhere". If tests fail on master, then "we won't deploy". 

We don't have such an environment right now where we deploy right from `master`, except for sites using the Jetpack Beta Tester plugin running on Bleeding Edge. 

> wouldn't it just be easier if they failed in the PR itself?

The merged code may start colliding with something else not present in the PR but present on master. PRs may sit there for sometime until they're re-tested again. We don't give any tools to developers to fix something if it fails with latest bleeding edge WordPress and PHP 5.2.

**Comment by abidhahmed** [comment]
Moving this to 6.5 milestone.

**Comment by oskosk** [comment]
Closing as no longer valid
